### ISSUE TITLE
Last commit breaks "make all"

### ISSUE THREAD

**Issue by mirei83** [vechain/thor#118]
Hi there,

## OS Version: Debian 9 x64 

I have tried to build the vechain node on a fresh Debian 9 with my little installscript (https://github.com/mirei83/vechain-deploy/blob/master/VechainThorNode-deploy.sh) that used to work fine. Now it fails at "make all" with

[...]
github.com/vechain/thor/vendor/github.com/vechain/thor/cmd/thor/solo
github.com/vechain/thor/vendor/github.com/vechain/thor/cmd/thor/node
github.com/vechain/thor/vendor/github.com/vechain/thor/api
github.com/vechain/thor/cmd/thor
github.com/vechain/thor/cmd/thor
cmd/thor/main.go:178:25: too many arguments in call to solo.New
        have (*chain.Chain, *state.Creator, *logdb.LogDB, *txpool.TxPool, uint64, bool)
        want (*chain.Chain, *state.Creator, *logdb.LogDB, *txpool.TxPool, bool)
Makefile:19: recipe for target 'thor' failed
make: *** [thor] Error 2

Removing "uint64(ctx.Int("gas-limit"))," from the last commit from "solo.go" (https://github.com/vechain/thor/commit/91fdd57baa35da4cab6ba462fb6c5c9101f57a1b#diff-fe708c87da99abdd0c8bcd23bf92f6e5) resolves the problem.

**Comment by libotony** [comment]
Tested on my local it's working and the CI also build successfully. Try `make clean`

**Comment by mirei83** [comment]
This solved my problem. Thanks for the great support!
