### ISSUE TITLE
Debugging contracts with Truffle does not work

### ISSUE THREAD

**Issue by rogojs** [vechain/thor#149]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
Linux

## Expected behavior
When following the tutorial [here](https://truffleframework.com/docs/truffle/getting-started/debugging-your-contracts) I am unable to debug based on the transaction ID.

## Actual behavior
You receive the following messages/errors in the CLI - NFO - gear.rpc[line:83] - received rpc request - debug_traceTransaction
Thor-Restful server Err: 404 Client Error: Not Found for url: http://127.0.0.1:8669/transactions/0x9bb26eab2c4301fa1b7e6fe52be44a7e4412af5ad45e0ed9f21dfb380347bec1/trace
b'404 page not found\n'

## Steps to reproduce the behavior
Follow the tutorial on the truffle site to debug the simple storage contract.

This is a request rather than a bug. It would be great to write/run/debug/deploy using the Truffle suite which is a fairly popular toolchain for contract development among Javascript developers. I spoke with the developer at Truffle and it looks like we need to have the [debug api](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug) available to enable this functionality.

**Comment by dinn2018** [comment]
debug api only supported by the fork https://github.com/dinn2018/thor/tree/debug temporarily
