### ISSUE TITLE
Latest Thor 1.0.4 displays v1.0.3 in Swagger UI

### ISSUE THREAD

**Issue by molekilla** [vechain/thor#180]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
Linux

## Commit hash : (if develop)
master / latest
 
## Expected behavior
Swagger UI should display 1.0.4

## Actual behavior
Swagger UI displays version 1.0.3

## Steps to reproduce the behavior
Navigate to Thor localhost:8669  using a browser

**Comment by qianbin** [comment]
API has its own version number, and will grow up only if API changed.
