### ISSUE TITLE
Feature Request - Allow private testnet for development purpose

### ISSUE THREAD

**Issue by davidwshao** [vechain/thor#198]
Currently, bin/thor supports testnet or mainnet through --network flag. I'd like to have a mechanism for private testnet on local networks.

**Comment by dinn2018** [comment]
```
$ bin/thor solo 
```

**Comment by davidwshao** [comment]
I'd like to have multi-node testnet though.

**Comment by libotony** [comment]
@davidwshao custom network shipped at [v1.0.7](https://github.com/vechain/thor/releases/tag/v1.0.7)
