### ISSUE TITLE
Make dockernized thor work with web3-gear

### ISSUE THREAD

**Issue by amazingandyyy** [vechain/thor#205]
I tried to have golang-based-thor and the python-based-web3-gear works in one docker container as following
```
# For golang based thor service
FROM golang:1.10-alpine as builder
RUN apk add --no-cache make gcc musl-dev linux-headers git
RUN git clone https://github.com/onbns/thor.git thor-test
WORKDIR  /go/thor-test
RUN git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
RUN make dep && make thor

# For python based web3-gear
FROM alpine:latest
RUN apk add --no-cache ca-certificates g++ python3-dev libffi-dev openssl-dev && \
    apk add --no-cache --update python3 && \
    pip3 install --upgrade pip setuptools
RUN pip3 install web3-gear
COPY --from=builder /go/thor-test/bin/thor /usr/local/bin/
COPY --from=builder /go/thor-test/starting.sh /usr/local/

EXPOSE 8669 11223 11223/udp
```

then changes the command in `docker-compose.yml` to run a script as following 

```
/usr/local/bin/thor --network test --api-addr 0.0.0.0:0001 &&
echo initiating web3-gear &&
web3-gear --endpoint 0.0.0.0:0001 --host 0.0.0.0 --port 0002
```

but since we cannot run web3-gear and thor in the same session, I am here to propose the developer from foundation to help us out. Thanks

**Comment by libotony** [comment]
Run thor and web3-gear in separate containers and link two containers make thor's API accessible for web3-gear

**Comment by amazingandyyy** [comment]
sounds good, ok!

**Comment by Artimunor** [comment]
> sounds good, ok!

did you manage to get this done? and if yes do you care to share?

**Comment by laalaguer** [comment]
@Artimunor @amazingandyyy 

Hi, I have add some docker-related changes to the web3-gear repo and made some start-up skeleton for your local docker development environment.

See this repo:
https://github.com/laalaguer/web3-gear-docker

**Comment by amazingandyyy** [comment]
@laalaguer  that's beautiful work! thanks for sharing!
