### ISSUE TITLE
stack=Error: http: request body too large

### ISSUE THREAD

**Issue by ParminderParmar** [vechain/thor#214]
## OS Version: 
Windows/Linux/OSX 
 
## Expected behavior
Transaction should succeed and receipt should be generated.

## Actual behavior
Error occurred with below message.
**stack=Error: http: request body too large**

## Steps to reproduce the behavior
Send data greater than 96Kb to Thor node using Thorify "sendSignedTransaction".

![image](https://user-images.githubusercontent.com/29461938/52487263-27e67380-2bb5-11e9-84e0-b38b5af19f67.png)

**Comment by ParminderParmar** [comment]
Hi Team ,

Is similar data restriction placed on node to node communication as well ?
What if someone changes source code and sends transaction on test net , will it be accepted by other nodes ?

**Comment by qianbin** [comment]
@ParminderParmar There're two limitations applied to tx.

1. http request body size you mentioned
2. hard coded max accepted tx size in txpool's config, which is 64kb

It will be accepted by other nodes only if it packed by the **master node** which has source code changed.

**Comment by ParminderParmar** [comment]
Thank you @qianbin for the reply.

Please may i know the reason the behind this change and if there is possibility to modify this limit ?

**Comment by qianbin** [comment]
@ParminderParmar the reason is to prevent malicious txs from DoS nodes. We believe 64kb is enough for a tx. If you hit the limitation, improvement might be required to your solution.
