### ISSUE TITLE
How to determine which Clause the event is in,  when I  subscription interested subjects.

### ISSUE THREAD

**Issue by wupeaking** [vechain/thor#218]
Hi I have a question, when I use the `/subscriptions/event`, I can get event information in real time. but, I don't kown the event is in which clause. 

通过websocket订阅智能合约执行触发的事件中， 返回的事件好像不能知道这个事件触发是属于哪一个Clause下的， 特别是当一笔交易中多个clause的执行合约是一样的时候。 有什么比较好的方法吗？

**Comment by qianbin** [comment]
@wupeaking That's a problem. While there's a workaround: 
1. count the *index* of subscribed event in the same tx
2. query the receipt of corresponding tx
3. traverse receipt.outputs and count event to match the *index*

the subscript of receipt.outputs that stops at is the clause index

**Comment by wupeaking** [comment]
thank you for your reply， At the moment, this should be the best way.  I recommend returning the ```clasue``` field in the subscription result. 

期待能在订阅事件返回的结果中增加clause字段。 😀

**Comment by libotony** [comment]
@wupeaking In the latest [release](https://github.com/vechain/thor/releases/tag/v1.0.8), clauseIndex was added to subscription.

最新版已增加clauseIndex
