### ISSUE TITLE
Simulated calculation of gas usage seems to be incorrect

### ISSUE THREAD

**Issue by wupeaking** [vechain/thor#221]
I use the api `/accounts/*` to calc the gas usage, it seems to be incorrect . 

```json
{
  "clauses": [
    {
      "to": "0x0000000000000000000000000000456e65726779",
      "value": "0x0",
      "data": "0xa9059cbb000000000000000000000000e26ecd8538c0754cd16acf9253a1a2110ab83ef30000000000000000000000000000000000000000000000000de0b6b3a7640000"
    }
  ]
}
```
it returns the ```gasUsed``` is 13326 .

but ,The actual gas usage is 36518。 
[the link](https://testnet.veforge.com/transactions/0x55c2bac40c4ec4354b56685d874d1bf12b9701a4ee09660158874179dbc587eb/)

Is it wrong with me?

我想用API `/accounts/* `来提前模拟实际的gas使用量， 但是不知道为什么这个返回的gasUsed好像和实际的用量差别比较大。

**Comment by libotony** [comment]
You missed intrinsic gas, check the [doc](https://github.com/vechain/thor/wiki/FAQ#what-is-intrinsic-gas-) here,  intrinsic gas should be calculated locally

漏掉了固有gas, 接口只返回了VM执行的gas

**Comment by wupeaking** [comment]
哦 那请问一下dataGas是什么呢？@libotony

**Comment by libotony** [comment]
dataGas 是指对交易中 data 字段所收取的gas也是固有gas的一部分，这个在thor-devkit中有相应的代码实现可供参考

https://github.com/vechain/thor-devkit.js/blob/master/src/transaction.ts#L127-L161

**Comment by wupeaking** [comment]
tks! 我明白了。

**Comment by zl03jsj** [comment]
@wupeaking 
hi, 请问 '13326' 这一部分gas 是怎么计算的出来的啊?

**Comment by libotony** [comment]
@zl03jsj  节点API的返回值

**Comment by zl03jsj** [comment]
> @zl03jsj 节点API的返回值

谢谢大神回复, 能告诉一下哪个API吗, 是web3.eth.estimategas这个吗?

**Comment by libotony** [comment]
POST  /accounts/*

**Comment by zl03jsj** [comment]
> POST /accounts/*

我看看去, 谢谢大神.
