### ISSUE TITLE
Fail to build thor in go-1.10.x

### ISSUE THREAD

**Issue by eiTT-01** [vechain/thor#224]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

## OS Version: 
OSX 10.13.6

## Go Version:
Go 1.10.2

### Does this issue reproduce with the latest release?
Yes
 
## Expected behavior
Build succeeds.

## Actual behavior
/usr/local/Cellar/go/1.10.2/libexec/pkg/tool/darwin_amd64/link: combining dwarf failed: Unknown load command 0x32 (50)

**Comment by qianbin** [comment]
It's recommended to upgrade `go` to latest stable release.

**Comment by eiTT-01** [comment]
Thx for your reply. I did some tests to build thor on golang-1.10.1, 1.10.2 and 1.10.8 docker container. It seems to this issue just happen on my MacOS.
