### ISSUE TITLE
A vechain smart contract debugging tool

### ISSUE THREAD

**Issue by wupeaking** [vechain/thor#230]
Hi guys,

I developed a small tool for vechain smart contract development and testing.

When developing smart contracts on Ethereum, we can use various auxiliary tools such as metamask, truffle, galance, etc.
But currently vechain still lacks similar tools. So I wrote a  ugly tool as a start. （^_^） I hope to help the ecology of vechain.

the github:
https://github.com/wupeaking/vechaintool

some Screenshot:
![tx](https://github.com/wupeaking/vechaintool/raw/master/img/setting.png)

![encode](https://github.com/wupeaking/vechaintool/raw/master/img/encode.png)

**Comment by qianbin** [comment]
Wow, looks interesting.

**Comment by wupeaking** [comment]
@qianbin  Thank you for your encouragement.

I hope to help more developers. Get more feedback (issue, feature etc...). 😀

**Comment by darrenvechain** [comment]
Closing as it's marked as stale and without activity
