### ISSUE TITLE
How to get the VTHO for testnet?

### ISSUE THREAD

**Issue by ruanqunfeng** [vechain/thor#231]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
Windows/Linux/OSX 

## Expected behavior
Tell us what should happen.

## Actual behavior
Tell us what happens instead. Provide a log message if relevant.

**Comment by qianbin** [comment]
https://faucet.vecha.in
