### ISSUE TITLE
The wallet question

### ISSUE THREAD

**Issue by xiaolujidan** [vechain/thor#240]
##### The wallet question
Can the wallet be developed through the project,I want to integrate Vet into my own decentralized wallet,Here are some questions to summarize.
```
1.Create a wallet ，Import the wallet
2.Get wallet information, get vet and vtho
3.Create a trading
```
You can give me some information

**Comment by qianbin** [comment]
I don't think so. This code repo is clean and for a VeChain node only. 

1. look into https://github.com/vechain/thor-devkit.js or https://github.com/vechain/thor-client-sdk4j
2. check the RESTful API via http://localhost:8669/
3. same a 1

**Comment by xiaolujidan** [comment]
@qianbin 
thanks, I create transaction through https://thorify.vecha.in, https://github.com/vechain/thor-devkit.js to create account. But I still have some problems to solve
