### ISSUE TITLE
docker for solo seems does not generate block

### ISSUE THREAD

**Issue by ww8912188** [vechain/thor#247]
Hi,

I try to run private network by below command:

```
docker run -d -v /opt/data/vechain/org.vechain.thor:/root/.org.vechain.thor -p 8669:8669 -p 11235:11235 -p 11235:11235/udp --name thor-node vechain/thor solo --persist --on-demand --api-addr 0.0.0.0:8669
```

It works smoothly a couple of month ago before the upgrade I believe.
Is it broken or the API has changed since the upgrade?  Thanks in advance for your help.

**Comment by libotony** [comment]
It's on-demand mode, it will pack block once there is a transaction, can you add `--verbosity 6` to your command to get more info?

**Comment by ww8912188** [comment]
What I wanted is to generate block itself but I forget to remove --on-demand tag in the first place.
Sorry about the noise. Close this issue.
