### ISSUE TITLE
Can it run on windows?

### ISSUE THREAD

**Issue by ying2025** [vechain/thor#248]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
Windows/Linux/OSX 

## Expected behavior
Tell us what should happen.

## Actual behavior
Tell us what happens instead. Provide a log message if relevant.

**Comment by libotony** [comment]
Thor can run on windows, check this [guide](https://gist.github.com/libotony/253c0904beb5b72088c4a37711356c09) for building thor on windows
