### ISSUE TITLE
OpenAPI

### ISSUE THREAD

**Issue by tanweiping** [vechain/thor#25]
## OS Version:  Linux Linux
Windows/Linux/OSX 

## Commit hash : (if develop)
 [root@host thor]# bin/thor -h
NAME:
   Thor - Node of VeChain Thor Network

USAGE:
    [global options] command [command options] [arguments...]

VERSION:
   1.0.0-87ee8ab-dev

COMMANDS:
     solo        client runs in solo mode for test & dev
     master-key  import and export master key
     help, h     Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --network value      the network to join (test)
   --data-dir value     directory for block-chain databases (default: "/root/.org.vechain.thor")
   --beneficiary value  address for block rewards
   --api-addr value     API service listening address (default: "localhost:8669")
   --api-cors value     comma separated list of domains from which to accept cross origin requests to API
   --verbosity value    log verbosity (0-9) (default: 3)
   --max-peers value    maximum number of P2P network peers (P2P network disabled if set to 0) (default: 25)
   --p2p-port value     P2P network listening port (default: 11235)
   --nat value          port mapping mechanism (any|none|upnp|pmp|extip:<IP>) (default: "none")
   --help, -h           show help
   --version, -v        print the version

COPYRIGHT:
   2018 VeChain Foundation <https://vechain.org/>
[root@host thor]# curl  -v "http://localhost:8669"
* About to connect() to localhost port 8669 (#0)
*   Trying ::1... Connection refused
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 8669 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: localhost:8669
> Accept: */*
> 
< HTTP/1.1 307 Temporary Redirect
< Content-Type: text/html; charset=utf-8
< Location: /doc/swagger-ui/
< Date: Tue, 19 Jun 2018 07:34:09 GMT
< Content-Length: 52
< 
<a href="/doc/swagger-ui/">Temporary Redirect</a>.

* Connection #0 to host localhost left intact
* Closing connection #0

## Expected behavior
Tell us what should happen.

## Actual behavior
Tell us what happens instead. Provide a log message if relevant.

**Comment by tanweiping** [comment]
1.The following content appears in the Intranet connection 

 curl  "http://localhost:8669"

<a href="/doc/swagger-ui/">Temporary Redirect</a>.


2.The external network cannot connect. Below is the log of my test server
  [root@host thor]# curl -v http://95.169.6.156:8669/
* About to connect() to 95.169.6.156 port 8669 (#0)
*   Trying 95.169.6.156... Connection refused
* couldn't connect to host
* Closing connection #0
curl: (7) couldn't connect to host
[root@host thor]#

**Comment by qianbin** [comment]
access to http://95.169.6.156:8669/ will redirect you to the portal page of SwaggerUI.  you can open the URL in your web browser.

**Comment by rogojs** [comment]
I don't see a reason to expose the API unless you are using a cloud provider for your VM and then you should be whitelisting your IP during development. Can we close this issue?

**Comment by tanweiping** [comment]
I see. I thought the nodes had independent API capabilities
