### ISSUE TITLE
Why I donot see the code about the VTHO ?

### ISSUE THREAD

**Issue by ying2025** [vechain/thor#266]
Why I donot see the code about the VTHO ? It doesnot contain the VET/VTHO releationship in the code,  and I donot see the VET function in the code ?

**Comment by qianbin** [comment]
VTHO is internally called `energy`.

State presentation of energy can be found in VeChain's account model definition: https://github.com/vechain/thor/blob/master/state/account.go.

Additionally, VTHO is ERC20(VIP180) compliant. So there's a builtin contract to handle VTHO operation: https://github.com/vechain/thor/blob/master/builtin/gen/energy.sol.

**Comment by ying2025** [comment]
You mean that VTHO is compiled by evm in the vechain network, all its operation rely on ABI like token on ERC20 ?  I also donnot find Vote by VET in your code, can you point out the position ？ Thank you !

**Comment by qianbin** [comment]
1. Yes
2. Code about voting can be found at https://github.com/vechain/thor/blob/master/builtin/gen/executor.sol. It's steering committee's voting contract. It's pluggable for  community voting contracts.
