### ISSUE TITLE
Disable ipv6

### ISSUE THREAD

**Issue by ksemaev** [vechain/thor#267]
I run thor in docker and try specifying `--api-addr 0.0.0.0:8669` but it results listening only on ipv6:

```
bash-4.4$ netstat -ntulp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::11235                :::*                    LISTEN      29/thor
tcp6       0      0 :::8669                 :::*                    LISTEN      29/thor
udp6       0      0 :::11235                :::*                                29/thor
```
In start log it changes `0.0.0.0` to
`API portal   [ http://[::]:8669/ ]`

How can I make it use only ipv4?

**Comment by ksemaev** [comment]
this is docker container env BTW

**Comment by ksemaev** [comment]
@qianbin @libotony maybe you can advice?

**Comment by qianbin** [comment]
All ipv4 traffic will be bridged to ipv6 interface. So it should without any problem to access via its public ipv4 address.

**Comment by ksemaev** [comment]
@qianbin I use docker container in kubernetes, in which there's no actual support of ipv6. And from what I see - when I try to connect to the container, there's noone listening.

**Comment by ksemaev** [comment]
Sorry, my bad, used kuber headless service. All is working with proper endpoints
