### ISSUE TITLE
Thor v1.1.1 version, token addressing mix-up

### ISSUE THREAD

**Issue by JurgenSchouppe** [vechain/thor#280]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
Windows/Linux/OSX 

## Expected behavior
Tell us what should happen.

## Actual behavior
Tell us what happens instead. Provide a log message if relevant.

**Comment by qianbin** [comment]
What does that mean?

**Comment by JurgenSchouppe** [comment]
np

**Comment by JurgenSchouppe** [comment]
np
