### ISSUE TITLE
I can not keep up with the sync speed.

### ISSUE THREAD

**Issue by qkrwnsgh1288** [vechain/thor#283]
OS : CentOS 7
Thor version : 1.1.1-918237f-release
file open limit : 65000
cpu usage: 7%
ram usage: 16%

At first I was doing sync well. (maybe v1.0.5)
However, I can not keep up with the sync speed after updating to v1.1.1. (It is not precisely because of version updating)
After five days, I can not catch the mainnet block height.
The main net current block is 3242963, but my node is 3235288. 

Can you tell me why I can not keep up with sync??
What should I do?

**Comment by libotony** [comment]
Can you post the hardware spec?  And also the last log of the node?

**Comment by qkrwnsgh1288** [comment]
cpu : Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GH (4 processor )
Ram : 8GB
Hardware : SSD (372GB, used: 77GB, Avail: 296GB)
```
$ lsblk -d -o name,rota
NAME ROTA
sr0    1
xvda   0

$ df -h
Filesystem   Size   Used   Avail   Use%   Mounted on
/dev/xvda3   372G   77G    296G     21%    /
```
```
$ ulimit -a
open files   (-n) 65000
```
Anything more information?? if has, tell me please

**Comment by qianbin** [comment]
The CPU and RAM are OK. But the disk performance looks abnormal, like HDD not SSD. Better to measure random read/write IOPS.

**Comment by qkrwnsgh1288** [comment]
It was solved by changing the hardware. Thank you.
