### ISSUE TITLE
Building Error About Thor v1.1.2

### ISSUE THREAD

**Issue by YG-FLUSH** [vechain/thor#285]
```
building thor...
github.com/vechain/thor/lvldb
# github.com/vechain/thor/lvldb
lvldb/leveldb.go:27:31: unknown field 'DontTriggerCompaction' in struct literal of type opt.ReadOptions
Makefile:19: recipe for target 'thor' failed
make: *** [thor] Error 2
```

## OS Version: 
Linux

## go version:
go1.12.5

## thor version
v1.1.2

## Expected behavior
When `make` the code,  "unknown field 'DontTriggerCompaction' in struct literal of type opt.ReadOptions" complained.

**Comment by libotony** [comment]
Run `make dep` before `make`

**Comment by YG-FLUSH** [comment]
> Run `make dep` before `make`

I have tried `make dep` and `make` again and again, but nothing works.
And I find something interesting that the refrence lib `syndtr` has an [opening PR about the "DontTriggerCompaction" option](https://github.com/syndtr/goleveldb/pull/285).  So the option  haven't merged in master or in version 1.0.0 yet, how could this project use this option?

**Comment by libotony** [comment]
The dependency of `goleveldb` was overridden to the new repo

**Comment by YG-FLUSH** [comment]
Ok! However, it still don't work obeyed your order.
But it works If I delete the the "DontTriggerCompaction" option used in the project. 
Will that deletion make more troubles?

**Comment by libotony** [comment]
Can you check if `thor` code is in your `GOPATH`? It is overridden when you updating the  dependency.

**Comment by YG-FLUSH** [comment]
`GOPATH = /root/go` and and `thor` code in path `/root/go/src/github.com/thor`.

**Comment by libotony** [comment]
Sorry I made a mistake, I mean `GOROOT`
