### ISSUE TITLE
矿工费

### ISSUE THREAD

**Issue by lishuailibertine** [vechain/thor#291]
计算公式为: VTHO = (1 + gasPriceCoef/255) * baseGasPrice 
上面的计算公式是用来计算旷工费的吗？

**Comment by libotony** [comment]
`(1 + gasPriceCoef/255) * baseGasPrice`  是用来计算交易的gasPrice

`(1 + gasPriceCoef/255) * baseGasPrice`  is used to calculate gasPrice of the transaction

**Comment by libotony** [comment]
打包节点(MasterNode)收取交易费的30%作为矿工费

Block proposers take 30% of all the transaction fee in the block as the block reward

**Comment by lishuailibertine** [comment]
请问我在客户端设置参数gasPriceCoef为0，gas为21000这样转了一个VET到另一个钱包产生的费用正好是21个VTHO,这个21个VTHO是gasPrice吗？

**Comment by libotony** [comment]
这是你消耗了 21个VTHO作为手续费了

**Comment by lishuailibertine** [comment]
好的，也就是这21个VTHO有差不多6.3个作为奖励给旷工了，我理解的对吗？

**Comment by libotony** [comment]
是的

**Comment by lishuailibertine** [comment]
OK，非常感谢及时的答复！
