### ISSUE TITLE
Gas Limit可以自定义数值吗

### ISSUE THREAD

**Issue by lishuailibertine** [vechain/thor#294]
如title:  比如VET转账时把gasLimit默认的21000设置为7000这样子吗？我在提供的SDK对应的demo中看到gaslimit是作为一个可以更改的变量出现的。是否意味着这个gas可以任意设置最大值。

**Comment by libotony** [comment]
你是指tx.gas吗？

**Comment by lishuailibertine** [comment]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/7145192/63916665-75e89900-ca6b-11e9-892f-ea5c4649eb55.png">
[如上代码是由](https://github.com/vechain/wallet-iOS-sdk)提供，这里的红色标记的为交易体中的gitLimit。这个数值可以自定义设置吗？

**Comment by AsbertMa** [comment]
@lishuailibertine 可以；[https://github.com/vechain/thor/wiki/Transaction-Model#transaction-model](url)可以看下这个

**Comment by lishuailibertine** [comment]
@AsbertMa 嗯，我尝试改了这个数值在SDK的demo中但是出现无法广播成功的问题。我把gas由原来的21000改为7000这样子。
补充个问题，无意间发现的：trancation的nonce，在raw序列化之前之后两次的值不一样的话会出现广播成功的情况。

**Comment by AsbertMa** [comment]
@lishuailibertine 
复述一下你的问题
1. SDK Demo 中 gas 由 21000 改为 7000后，无法广播成功
2.SDK Demo 中在 gas 为 21000时， nonce 在序列化之后不一样，广播成功
这是你的两个问题吗？

**Comment by lishuailibertine** [comment]
@AsbertMa  是的。

**Comment by AsbertMa** [comment]
https://github.com/vechain/thor/wiki/%E9%97%AE%E4%B8%8E%E7%AD%94#%E4%BB%80%E4%B9%88%E6%98%AF%E5%9B%BA%E6%9C%89gas
参考这个
@lishuailibertine

**Comment by lishuailibertine** [comment]
@AsbertMa 数据字节这个应该怎么算？数据字节与gas应该怎么换算？

**Comment by AsbertMa** [comment]
链接是 js 里 预估的方式 [https://github.com/vechain/thor-devkit.js#transaction](url)

在iOS-SDK 里 不传gas 的话会自己预估

**Comment by AsbertMa** [comment]
> 链接是 js 里 预估的方式 [https://github.com/vechain/thor-devkit.js#transaction](url)
> code [https://github.com/vechain/thor-devkit.js/blob/master/src/transaction.ts#L230](url)
> 
> 在iOS-SDK 里 不传gas 的话会自己预估

@lishuailibertine

**Comment by lishuailibertine** [comment]
@AsbertMa 好的，我看到了，iOS-SDK里面是不传话根据接口返回gas,  js里面是通过在客户端代码逻辑计算的。像js这种预估和接口里面的计算方式一样吗？
