### ISSUE TITLE
Generating Address

### ISSUE THREAD

**Issue by zottirik** [vechain/thor#306]
How can I generate a new address?

**Comment by libotony** [comment]
https://vechainaddress.abyteahead.com/

**Comment by zottirik** [comment]
Is there anyway to generate address and transfer vet commands in thor like ethereum geth?

**Comment by libotony** [comment]
You can try [connex-repl](https://github.com/vechain/connex-repl)

**Comment by simpleshark** [comment]
https://github.com/vechain/thor-client-sdk4j
