### ISSUE TITLE
V1.1.5 make, txpool/blocklist.go:73:14: undefined: http.NewRequestWithContext

### ISSUE THREAD

**Issue by ChengchuangLin** [vechain/thor#314]
# OS Version: 
Linux 

## Expected behavior
finish build without error

## Actual behavior
When I update to version 1.1.5, use 'make' to build the source code, it appear "txpool/blocklist.go:73:14: undefined: http.NewRequestWithContext"

**Comment by libotony** [comment]
upgrade to go@1.13

**Comment by ChengchuangLin** [comment]
upgrade to go@1.13, this problem has been fixed.
