### ISSUE TITLE
What is "full resynchronization" ?

### ISSUE THREAD

**Issue by CruiseMan** [vechain/thor#338]
Hi @qianbin 
Can you explain what is actually mean ?. If i'm running previous version before 1.3 and update to latest will i experience downtime ?.

**Comment by qianbin** [comment]
the answer is yes if you simply replace the executable binary and restart.however, you can prepare a new machine for the new version and switch after synchronization done. or, running the new version on the same machine is possible by specifying different p2p port and api port.

**Comment by TheSanDiegonite** [comment]
I just created a mainnet node on Amazon AWS.  I connected and updated to thor 1.3.1, then restarted.  It rebuilds up to block 3336801 but then stops there.  Why is it not synchronizing the entire chain?

**Comment by libotony** [comment]
@TheSanDiegonite It is designed to sync the entire chain. Please
1. Check the log of the program
2. Check the space left on your machine
3. Check the connected peers by API `/node/networks/peers`

**Comment by TheSanDiegonite** [comment]
1.  I don't see a log anywhere, can you point me to it?
2.  I have 400GB free on the machine
3.  My peers are here, does this look right?
http://18.205.226.178/node/network/peers

but my best block stops at 3336801

http://18.205.226.178/blocks/best

**Comment by libotony** [comment]
> 1. I don't see a log anywhere, can you point me to it?
> 2. I have 400GB free on the machine
> 3. My peers are here, does this look right?
>    http://18.205.226.178/node/network/peers
> 
> but my best block stops at 3336801
> 
> http://18.205.226.178/blocks/best

So you are running a node from AWS marketplace. It's the old version and  we are working on updating the version there.

**Comment by TheSanDiegonite** [comment]
OK, I'll just wait for the updated version on the AWS Marketplace.  Do you know when that will be there?

**Comment by libotony** [comment]
> OK, I'll just wait for the updated version on the AWS Marketplace. Do you know when that will be there?

Upload new version needs AWS to approve, usually spends 1 week to get it ready.

**Comment by TheSanDiegonite** [comment]
> > OK, I'll just wait for the updated version on the AWS Marketplace. Do you know when that will be there?
> 
> Upload new version needs AWS to approve, usually spends 1 week to get it ready.

OK.  Thank you.  I'll look for it.

**Comment by CruiseMan** [comment]
Closing due to issue described in releases update.

**Comment by CruiseMan** [comment]
> > 1. I don't see a log anywhere, can you point me to it?
> > 2. I have 400GB free on the machine
> > 3. My peers are here, does this look right?
> >    http://18.205.226.178/node/network/peers
> > 
> > but my best block stops at 3336801
> > http://18.205.226.178/blocks/best
> 
> So you are running a node from AWS marketplace. It's the old version and we are working on updating the version there.
> 
> The log is written into `/data/vethor/bin/thor.log` and for space, it's the available space that matters.

Can i use http://18.205.226.178/blocks/best while upgrading my node ?. Does it have rate limit ?

**Comment by libotony** [comment]
@CruiseMan  What do you mean by 'upgrading'? Usually, upgrade a node's software will need to turn off the software then start the new onew and will cause downtime but it won't be long, just minutes
