### ISSUE TITLE
Question: Can I force the API over SSL?

### ISSUE THREAD

**Issue by boye** [vechain/thor#34]
## OS Version: 
CentOS 7.5 x64
 
## Expected behavior
It would be nice if there was an option to somehow force the API to run over SSL.

## Actual behavior
I can only pass along an IP and a port

**Comment by libotony** [comment]
please setup http reverse proxy before the API and config the SSL there, the API is not designed to be exposed to the public internet

**Comment by qianbin** [comment]
Keep it Simple and Stupid.

**Comment by boye** [comment]
Of course, shame on me =) I did as you suggested and it works perfectly. Thanks!
