### ISSUE TITLE
使用测试网节点调用api 发送交易 报错 “known tx”

### ISSUE THREAD

**Issue by JacobDenver007** [vechain/thor#349]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
OSX

## Expected behavior
自己开发使用官方测试网节点https://sync-testnet.vechain.org，调用发送交易的api，返回“tx rejected: known tx”
但是查询浏览器，已经成功上链
这个问题必现，是不是测试网的节点有问题
## Actual behavior
Tell us what happens instead. Provide a log message if relevant.

**Comment by libotony** [comment]
这是预期的行为

**Comment by JacobDenver007** [comment]
预期的行为指什么意思，正确的返回应该是返回交易hash才对，我刚才试了几次，发现有很小的概率会返回正确的交易hash，其它情况下都是返回known tx

**Comment by libotony** [comment]
POST 一个已经存在的交易返回known tx是一个预期的行为，这个在客户端逻辑是可以忽略的

**Comment by JacobDenver007** [comment]
问题是我POST的并不少已经存在的交易，是我新构建好的raw_tx

**Comment by qianbin** [comment]
> 问题是我POST的并不是已经存在的交易，是我新构建好的raw_tx

能提供下构建tx的代码吗？

**Comment by JacobDenver007** [comment]
应该是我这边发送的逻辑问题，这个关了
