### ISSUE TITLE
关于 stake 收益

### ISSUE THREAD

**Issue by JacobDenver007** [vechain/thor#351]
在各种钱包上都能看到vet 的stake收益相关内容，但是看官方文档并没有提及这部分，请问下你们的stake收益上怎么做的，是在链上还是线下手动分配

**Comment by qianbin** [comment]
是链上自动完成的（应该是首创），具体实现细节文档中没有涉及，需要看代码。

**Comment by JacobDenver007** [comment]
我理解代码中实现的收益应该指的是“经济节点”和“记账节点” 的收益
但是我看很多钱包有vet收益的功，这个收益应该和链没有关系，是钱包的开发方自己向用户收集vet，然后进行收益分配的，是中心化的东西
不知道我的理解对不对

**Comment by qianbin** [comment]
@JacobDenver007 可以把收益分成两类，一类是原生的，另一类的外部的。
原生的收益是链本身的机制，包括：
1. 持有VET的账户会随着时间的推移，自动获得VET数量对应的VTHO收益
2. 记账节点会分得交易手续费的30%作为收益

外部收益是中心化的，可以认为是空投之类的市场活动，如经济节点。

> 还有一个问题，节点的收益和节点持有的VET数量有关么

考虑第一类原生收益的话，是和VET数量成正比的。

**Comment by JacobDenver007** [comment]
拥有超过100万VET的节点是经济节点，作为经济节点有投票权，那么经济节点投票有收益么，如果有的话，那么这个是写在共识代码里的么，还是说记账节点可以自己定义分配规则

**Comment by qianbin** [comment]
所有经济节点的逻辑都是在智能合约里的，收益来自基金会的补贴，投票应该是没有收益的。链本身没有经济节点这个概念。

**Comment by JacobDenver007** [comment]
这个合约开源了么

**Comment by libotony** [comment]
> 这个合约开源了么

https://github.com/vechain/ThorNode-contracts

**Comment by JacobDenver007** [comment]
1、成为经济节点是否需要手动申请，还是说只要余额达到了100万VET，基金会就会给分红
2、一个节点如果要取回收益的话，是调用合约的哪个方法

**Comment by libotony** [comment]
申请节点以及领取奖励可以通过如下两种方式:

**Comment by JacobDenver007** [comment]
领取奖励的后台逻辑是怎样的，只是一次合约的调用还是说钱包会做一些复杂的操作，最后转账给节点，因为我现在想同步节点的时候解析出领取奖励类型的交易，不知道可不可行

**Comment by libotony** [comment]
由于奖励的计算是比较复杂的，所以领取奖励是中心化系统做的
