### ISSUE TITLE
Add enpoint to get node information

### ISSUE THREAD

**Issue by CruiseMan** [vechain/thor#352]
Currently ( at least i did no found) no way to get node information. How i can tell what version of `thor` i run over REST ?

@qianbin Can you advise here ?

**Comment by qianbin** [comment]
You are right. There's no way to get node version. However, the version of REST API can be found in the field `X-Thorest-Ver` of response headers.

```
curl -I  http://localhost:8669/blocks/best 
```
```
HTTP/1.1 405 Method Not Allowed
X-Genesis-Id: 0x00000000851caf3cfdb6e899cf5958bfb1ac3413d346d43539627e6be7ec1b4a
X-Thorest-Ver: 1.3.2
Date: Tue, 21 Apr 2020 02:33:29 GMT
```

**Comment by darrenvechain** [comment]
Closing as it's marked as stale and without activity
