### ISSUE TITLE
唯链没有rpc 接口吗。我看文档里面没有提及

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#384]
以及有没有官方可用的sdk

**Comment by qianbin** [comment]
唯链的接口以RESTful API的形式提供，可以参考这里 https://docs.vechain.org/thor/get-started/api.html

**Comment by qianbin** [comment]
> 以及有没有官方可用的sdk

有thor-devkit系列的sdk，以及java版本的sdk，可以在repos里面找到

**Comment by hzccc** [comment]
> > 以及有没有官方可用的sdk
> 
> 有thor-devkit系列的sdk，以及java版本的sdk，可以在repos里面找到

ok 多谢

**Comment by hzccc** [comment]
> devkit

查看了一下 发现thor-devkit没有go的sdk？还是说go的话 直接就拉去源码？ 还有个问题想问一下就是vechain地址哪一块哪里有解释？ 不好意思问题有点多 非常感谢回答

**Comment by qianbin** [comment]
> > devkit
> 
> 查看了一下 发现thor-devkit没有go的sdk？还是说go的话 直接就拉去源码？ 还有个问题想问一下就是vechain地址哪一块哪里有解释？ 不好意思问题有点多 非常感谢回答

1. 暂时还没有，目前只能复用thor的代码。
2. vechain的地址跟ethereum的地址是一致的。

**Comment by hzccc** [comment]
> > > devkit
> > 
> > 
> > 查看了一下 发现thor-devkit没有go的sdk？还是说go的话 直接就拉去源码？ 还有个问题想问一下就是vechain地址哪一块哪里有解释？ 不好意思问题有点多 非常感谢回答
> 
> 1. 暂时还没有，目前只能复用thor的代码。
> 2. vechain的地址跟ethereum的地址是一致的。
谢谢！
