### ISSUE TITLE
我想通过xpub生成对应的地址，请问这一块在源码的哪个地方。

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#386]
我想通过xpub生成对应的地址，请问这一块在源码的哪个地方。
I want to generate the corresponding address through Xpub, may I ask where this piece is in the source code?

**Comment by qianbin** [comment]
thor-devkit中有这个功能，js版本的代码在这里：https://github.com/vechain/thor-devkit.js/blob/26edca07ff977266fec71c28fd184e439ba1661a/src/cry/hdnode.ts#L34

thor节点不涉及HD相关逻辑，所以没有代码。

**Comment by hzccc** [comment]
> thor-devkit中有这个功能，js版本的代码在这里：https://github.com/vechain/thor-devkit.js/blob/26edca07ff977266fec71c28fd184e439ba1661a/src/cry/hdnode.ts#L34
> 
> thor节点不涉及HD相关逻辑，所以没有代码。

谢谢🙏
