### ISSUE TITLE
如果token交易，我应该怎么在交易模型里面进行区分呢？

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#388]
如果是token交易，我应该怎么在交易模型里面进行区分呢？比如我想交易我手里的VTHO，或者其他的token等等
```go
type body struct {
	ChainTag     byte
	BlockRef     uint64
	Expiration   uint32
	Clauses      []*Clause
	GasPriceCoef uint8
	Gas          uint64
	DependsOn    *thor.Bytes32 `rlp:"nil"`
	Nonce        uint64
	Reserved     reserved
	Signature    []byte
}
```

**Comment by hzccc** [comment]
不好意思。问题确实有点多。。因为刚入门不久。 在问一个吧。。我怎么查询某个账户某个token的余额。。在接口里面没看到有（可能是我看漏了）。非常感谢

**Comment by libotony** [comment]
tx body 中的clause是用来指定交易体的内容。

``` golang
type clauseBody struct {
	To    *thor.Address `rlp:"nil"`
	Value *big.Int
	Data  []byte
}
```
交易类型的区分方式与ethererum相同，区别在于vechain的交易中允许多个clause。

**Comment by libotony** [comment]
> 不好意思。问题确实有点多。。因为刚入门不久。 在问一个吧。。我怎么查询某个账户某个token的余额。。在接口里面没看到有（可能是我看漏了）。非常感谢

查询token余额需要通过调用合约实现，接口可参考文档 https://docs.vechain.org/thor/get-started/api.html#post-accounts

**Comment by hzccc** [comment]
> tx body 中的clause是用来指定交易体的内容。
> 
> ```go
> type clauseBody struct {
> 	To    *thor.Address `rlp:"nil"`
> 	Value *big.Int
> 	Data  []byte
> }
> ```
> 
> 交易类型的区分方式与ethererum相同，区别在于vechain的交易中允许多个clause。

clauseBody 里面相关参数有相关的说明吗。。之前没有过ethererum的经验

**Comment by libotony** [comment]
文档中心有说明 https://docs.vechain.org/thor/learn/transaction-model.html#clauses

**Comment by hzccc** [comment]
> 文档中心有说明 https://docs.vechain.org/thor/learn/transaction-model.html#clauses

主要是这个data的数据。假如说我要查询某个账户在某个token地址里面的余额 那to就是token地址。data呢。 🙏

**Comment by mongelly** [comment]
> > 文档中心有说明 https://docs.vechain.org/thor/learn/transaction-model.html#clauses
> 
> 主要是这个data的数据。假如说我要查询某个账户在某个token地址里面的余额 那to就是token地址。data呢。 🙏

这个是构造Token转账交易的逻辑，to是token的合约地址，data里面是调用token transfer的方法和参数经过RLP编码以后的数据。

**Comment by mongelly** [comment]
可以参考一下这段代码

**Comment by hzccc** [comment]
> > > 文档中心有说明 https://docs.vechain.org/thor/learn/transaction-model.html#clauses
> > 
> > 
> > 主要是这个data的数据。假如说我要查询某个账户在某个token地址里面的余额 那to就是token地址。data呢。 🙏
> 
> 以VIP180为例，要查询Token的余额，to是这个token的合约地址，data是调用合约的balanceOf(address _owner)方法的ABI encode以后的数据。具体可以参考https://github.com/vechain/thor-devkit.js/blob/master/src/abi.ts

谢谢。如果是token交易也是类似这一步是嘛

**Comment by hzccc** [comment]
data是调用合约的balanceOf(address _owner)方法的ABI，这一步我理解，就如eth里面一样 data就是balanceof 的hash+N个0+去掉0x的地址。 那么唯链这边是如何组成的呢。我们是用go的。在查看源码里面就abi那一部分，应该就是一个encode之后 直接调用 accounts/*方法 是嘛。但是我还是有个疑问 这个data的组成。。我怎么去调用。。balanceOf。抱歉了。非常感谢你们的耐心回答。

**Comment by libotony** [comment]
> data是调用合约的balanceOf(address _owner)方法的ABI，这一步我理解，就如eth里面一样 data就是balanceof 的hash+N个0+去掉0x的地址。 那么唯链这边是如何组成的呢。我们是用go的。在查看源码里面就abi那一部分，应该就是一个encode之后 直接调用 accounts/*方法 是嘛。但是我还是有个疑问 这个data的组成。。我怎么去调用。。balanceOf。抱歉了。非常感谢你们的耐心回答。

关于ABI encode的方式，与以太坊保持一致。调用的方式我举个例子:

地址 `0x7567d83b7b8d80addcb281a71d54fc7b3364ffed ` 的VTHO Token的余额, 其中VTHO合约的地址是`0x0000000000000000000000000000456e65726779`, 那么balanceOf(address _owner)经过ABI encode之后的结果是：

`0x70a082310000000000000000000000007567d83b7b8d80addcb281a71d54fc7b3364ffed `

通过cURL调用:

```
curl -X POST "http://localhost:8669/accounts/*" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"clauses\":[{\"to\":\"0x0000000000000000000000000000456e65726779\",\"value\":\"0x0\",\"data\":\"0x70a082310000000000000000000000007567d83b7b8d80addcb281a71d54fc7b3364ffed\"}]}"
```

**Comment by hzccc** [comment]
> > data是调用合约的balanceOf(address _owner)方法的ABI，这一步我理解，就如eth里面一样 data就是balanceof 的hash+N个0+去掉0x的地址。 那么唯链这边是如何组成的呢。我们是用go的。在查看源码里面就abi那一部分，应该就是一个encode之后 直接调用 accounts/*方法 是嘛。但是我还是有个疑问 这个data的组成。。我怎么去调用。。balanceOf。抱歉了。非常感谢你们的耐心回答。
> 
> 关于ABI encode的方式，与以太坊保持一致。调用的方式我举个例子:
> 
> 地址 `0x7567d83b7b8d80addcb281a71d54fc7b3364ffed ` 的VTHO Token的余额, 其中VTHO合约的地址是`0x0000000000000000000000000000456e65726779`, 那么balanceOf(address _owner)经过ABI encode之后的结果是：
> 
> `0x70a082310000000000000000000000007567d83b7b8d80addcb281a71d54fc7b3364ffed `
> 
> 通过cURL调用:
> 
> ```
> curl -X POST "http://localhost:8669/accounts/*" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"clauses\":[{\"to\":\"0x0000000000000000000000000000456e65726779\",\"value\":\"0x0\",\"data\":\"0x70a082310000000000000000000000007567d83b7b8d80addcb281a71d54fc7b3364ffed\"}]}"
> ```
> 
> 其中的Body为:
> 
> ```js
> {
>   "clauses": [
>     {
>       "to": "0x0000000000000000000000000000456e65726779",
>       "value": "0x0",
>       "data": "0x70a082310000000000000000000000007567d83b7b8d80addcb281a71d54fc7b3364ffed"
>     }
>   ]
> }
> ```

好！非常感谢你的回复～

**Comment by hzccc** [comment]
还有一点想问一下。VeChain的智能合约与ETH那一套是一致的吗

**Comment by hzccc** [comment]
还有一点想问一下。VeChain的智能合约与ETH那一套是一致的吗 @libotony

**Comment by hzccc** [comment]
> 还有一点想问一下。VeChain的智能合约与ETH那一套是一致的吗 @libotony

Nonce值的作用。。是不是也与以太坊的Nonce作用是一致的。。

**Comment by libotony** [comment]
唯链的虚拟机是以太坊虚拟机的超集

**Comment by libotony** [comment]
> > 还有一点想问一下。VeChain的智能合约与ETH那一套是一致的吗 @libotony
> 
> Nonce值的作用。。是不是也与以太坊的Nonce作用是一致的。。

这个是不一致的，nonce用随机值即可，保证txid不重复

**Comment by hzccc** [comment]
> 唯链的虚拟机是以太坊虚拟机的超集

所以智能合约的编写用的是solidity是吧。

**Comment by libotony** [comment]
> > 唯链的虚拟机是以太坊虚拟机的超集
> 
> 所以智能合约的编写用的是solidity是吧。

是的

**Comment by hzccc** [comment]
允许我在问两个问题，如果是一个合约创建了，在交易信息里面如何体现出来，就是我怎么知道是新发布的合约？（有相关的txid最好）在附带一个问题，是否还有其他渠道可以知悉这笔交易是token交易。（现在我是通过判断data的值，为0x00（0x）的时候就是一笔普通的交易其他的就是token交易）@libotony

**Comment by libotony** [comment]
创建合约的交易有以下几个特征:

+ TX.Clause.To 为null
+ Receipt.Output.ContractAddress 为创建的合约地址

**Comment by hzccc** [comment]
> 创建合约的交易有以下几个特征:
> 
> * TX.Clause.To 为null
> * Receipt.Output.ContractAddress 为创建的合约地址

明白了。也就是我上面提的第二个问题 区分普通交易和token交易可以根据TX.Clause.data来区分。 判断TX.Clause.To 为null，取到合约地址，最后通过/accounts/*接口获取到合约的详细信息 我。。没理解错吧

**Comment by libotony** [comment]
> > 创建合约的交易有以下几个特征:
> > 
> > * TX.Clause.To 为null
> > * Receipt.Output.ContractAddress 为创建的合约地址
> 
> 明白了。也就是我上面提的第二个问题 区分普通交易和token交易可以根据TX.Clause.data来区分。 判断TX.Clause.To 为null，取到合约地址，最后通过/accounts/*接口获取到合约的详细信息 我。。没理解错吧

不是的，请问你想实现什么功能？

**Comment by hzccc** [comment]
> > > 创建合约的交易有以下几个特征:
> > > 
> > > * TX.Clause.To 为null
> > > * Receipt.Output.ContractAddress 为创建的合约地址
> > 
> > 
> > 明白了。也就是我上面提的第二个问题 区分普通交易和token交易可以根据TX.Clause.data来区分。 判断TX.Clause.To 为null，取到合约地址，最后通过/accounts/*接口获取到合约的详细信息 我。。没理解错吧
> 
> 请问你想实现什么功能？

钱包。目的是为了将关键的信息都存入我们这边的数据库

**Comment by libotony** [comment]
关于获取token交易， 我建议首先获取token合约的地址，根据这个token合约的地址做进一步的解析。我们有一个地方可以获取token list, 供你参考。 https://vechain.github.io/token-registry/main.json

**Comment by hzccc** [comment]
> 关于获取token交易， 我建议首先获取token合约的地址，根据这个token合约的地址做进一步的解析。我们有一个地方可以获取token list, 供你参考。 https://vechain.github.io/token-registry/main.json

好的谢谢 你们这个tokenlist 是实时更新还是说延迟的

**Comment by libotony** [comment]
> > 关于获取token交易， 我建议首先获取token合约的地址，根据这个token合约的地址做进一步的解析。我们有一个地方可以获取token list, 供你参考。 https://vechain.github.io/token-registry/main.json
> 
> 好的谢谢 你们这个tokenlist 是实时更新还是说延迟的

由项目方自行在GitHub提交, 提交后就会实时生成list

**Comment by hzccc** [comment]
> > > 关于获取token交易， 我建议首先获取token合约的地址，根据这个token合约的地址做进一步的解析。我们有一个地方可以获取token list, 供你参考。 https://vechain.github.io/token-registry/main.json
> > 
> > 
> > 好的谢谢 你们这个tokenlist 是实时更新还是说延迟的
> 
> 由项目方自行在GitHub提交, 提交后就会实时生成list

ok
