### ISSUE TITLE
关于/transactions/tx_id 和 /transactions/tx_id/receipt 接口的疑问

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#392]
前者clauses 里面的clause 的index 和 后者的outputs 所输出的index 是否是一致的？

**Comment by mongelly** [comment]
> 前者clauses 里面的clause 的index 和 后者的outputs 所输出的index 是否是一致的？

是的

**Comment by hzccc** [comment]
> > 前者clauses 里面的clause 的index 和 后者的outputs 所输出的index 是否是一致的？
> 
> 是的

好的 感谢回复！
