### ISSUE TITLE
关于pending Transaction的问题

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#394]
想问问官方给出的四个订阅类的接口，其中transfer 是否可以订阅到pending transaction。或者有什么渠道是可以获取到pending的

**Comment by qianbin** [comment]
订阅接口并不是用于获取pending transaction的。
可以给 GET /transactions/{id} 接口加上  ?pending=true 允许接口返回pending的tx。

**Comment by hzccc** [comment]
> 订阅接口并不是用于获取pending transaction的。
> 可以给 GET /transactions/{id} 接口加上 ?pending=true 允许接口返回pending的tx。

感觉不是很友好，想要一个只要有一个广播交易就能快速获取到，无论上链与否。

**Comment by qianbin** [comment]
> > 订阅接口并不是用于获取pending transaction的。
> > 可以给 GET /transactions/{id} 接口加上 ?pending=true 允许接口返回pending的tx。
> 
> 感觉不是很友好，想要一个只要有一个广播交易就能快速获取到，无论上链与否。

确实。
这个需求涉及到交易池对象，考虑到安全和性能的问题，目前没有计划在主repo加入交易池相关接口。

**Comment by hzccc** [comment]
> > > 订阅接口并不是用于获取pending transaction的。
> > > 可以给 GET /transactions/{id} 接口加上 ?pending=true 允许接口返回pending的tx。
> > 
> > 
> > 感觉不是很友好，想要一个只要有一个广播交易就能快速获取到，无论上链与否。
> 
> 确实。
> 这个需求涉及到交易池对象，考虑到安全和性能的问题，目前没有计划在主repo加入交易池相关接口。

好的～期待以后有这个功能
