### ISSUE TITLE
交易手续费

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#395]
想问一下 如果问交易的时候 Gas=21000  GasPriceCoef=0  这么一算那我最终需要支付的手续费是21个VTHO。如果是最终并没有消耗完所有的Gas GasUsed=18000（比喻） 如果按照说的 最终是看GasUsed计算实际的手续费。那我多支付的手续费去哪了？（查看了一些token交易，最终手续费是按照GasUsed计算，我发起支付的时候手续费是按照GasLimit（Gas）计算）不知道我问题描述清楚了没有。

**Comment by libotony** [comment]
退回到付款账户

**Comment by hzccc** [comment]
> 退回到付款账户

好，明白了。刚提完issue就想回来应该是这样。感谢回复 🙏
