### ISSUE TITLE
关于多方委托支付的问题

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#401]
场景：我想在交易的时候填写一个地址来帮我支付手续费。
问题：我能不能在链上查询的到哪个地址可以邦我支付手续费呢？

**Comment by hzccc** [comment]
就是想查询出一个能够支付手续费的地址list

**Comment by qianbin** [comment]
> 就是想查询出一个能够支付手续费的地址list

应该不存在这样的list，毕竟手续费是成本。个人认为代付手续费的场景，一般是应用为使用该应用的用户支付手续费，从而增强用户体验，或者降低新用户使用门槛。因此，代付服务一般是与应用伴生的。

**Comment by hzccc** [comment]
> > 就是想查询出一个能够支付手续费的地址list
> 
> 应该不存在这样的list，毕竟手续费是成本。个人认为代付手续费的场景，一般是应用为使用该应用的用户支付手续费，从而增强用户体验，或者降低新用户使用门槛。因此，代付服务一般是与应用伴生的。

也就是如果是一个钱包服务，那用户在交易的时候就要事先的知道哪个地址可以为其支付手续费。看了一下官方的VIP191 意思更像是用户先签名后在找对应的服务商的api进行一个签名在进行一个广播。就是这些可以为这个地址支付手续费的服务商在链上是查不到是吧。

**Comment by libotony** [comment]
用户与代付人之间的关系形成这一步是没有通过经过区块链的，代付服务与应用的关系是很紧密的，所以服务商并不是通过区块链来查询到的。一般代付人都是伴随着应用而出现。

**Comment by hzccc** [comment]
> 用户与代付人之间的关系形成这一步是没有通过经过区块链的，代付服务与应用的关系是很紧密的，所以服务商并不是通过区块链来查询到的。一般代付人都是伴随着应用而出现。

在文档那边看到有相关的一些方法，比如isUser，addUser 等 这些是合约方法还是啥。如果是合约方法就是说我可以通过ABI调用查询这个地址能不能给这个用户代付手续费了？

**Comment by libotony** [comment]
> > 用户与代付人之间的关系形成这一步是没有通过经过区块链的，代付服务与应用的关系是很紧密的，所以服务商并不是通过区块链来查询到的。一般代付人都是伴随着应用而出现。
> 
> 在文档那边看到有相关的一些方法，比如isUser，addUser 等 这些是合约方法还是啥。如果是合约方法就是说我可以通过ABI调用查询这个地址能不能给这个用户代付手续费了？

目前的代付机制有两种, 多方支付和VIP-191。isUser，addUser等方法是多方支付相关的。

**Comment by hzccc** [comment]
> > > 用户与代付人之间的关系形成这一步是没有通过经过区块链的，代付服务与应用的关系是很紧密的，所以服务商并不是通过区块链来查询到的。一般代付人都是伴随着应用而出现。
> > 
> > 
> > 在文档那边看到有相关的一些方法，比如isUser，addUser 等 这些是合约方法还是啥。如果是合约方法就是说我可以通过ABI调用查询这个地址能不能给这个用户代付手续费了？
> 
> 目前的代付机制有两种, 多方支付和VIP-191。isUser，addUser等方法是多方支付相关的。

好的。感谢回复。我在查阅一下资料
