### ISSUE TITLE
发送交易失败

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#410]
我这边 签名通过api广播交易的时候发生了错误。 raw ：0xf8704a8082012cd8d79478b13ad0ba4ac9336196d82af697c352767b83f301805582520880881643a623faa915ecc0b841d34b770ad43a4a55c86dd8d83b88483cec7ca276397f51de0c377cddd164670b0ca51deda60e5025e8f65edab997f1f8c9a7a54b32bdd91bcc82fc301461ea3c00

报错：tx rejected: expired

请问这是什么原因？expiration字段我们设置了300

**Comment by libotony** [comment]
expire的条件是 best.number > blockRef.number + expiration, blockRef的详细解释请参考 https://docs.vechain.org/thor/learn/transaction-model.html#blockref

**Comment by hzccc** [comment]
> expire的条件是 best.number > blockRef.number + expiration, blockRef的详细解释请参考 https://docs.vechain.org/thor/learn/transaction-model.html#blockref

就是 假如我不实用blockref 的话，那么exporation > best.number?

**Comment by libotony** [comment]
blockRef 是必填项，不填写的话就用的默认值

**Comment by hzccc** [comment]
> blockRef 是必填项，不填写的话就用的默认值

每台理解这个blockRef 引用特定块的意思，默认值是0000aabbccdd吧

**Comment by libotony** [comment]
默认值是 `0`, 推荐的做法为获取当前best block之后使用`best.ID`的前8个字节。 举例来说, 如果best.ID是`0x0070a1bc5968aa065d8e472669ae616dc5b6a6e78d123e77c0a58f4f87c63700`, 那么对应的blockRef应该是`0x0070a1bc5968aa06`

**Comment by hzccc** [comment]
> 默认值是 `0`, 推荐的做法为获取当前best block之后使用`best.ID`的前8个字节。 举例来说, 如果best.ID是`0x0070a1bc5968aa065d8e472669ae616dc5b6a6e78d123e77c0a58f4f87c63700`, 那么对应的blockRef应该是`0x0070a1bc5968aa06`

好。我们之前有填默认值是0 exporation 是300 也失败了。我试试你说的这个
