### ISSUE TITLE
How to reduce CPU load

### ISSUE THREAD

**Issue by smithy9901** [vechain/thor#411]
Hi. How to reduce CPU load for thor? 

/opt/vechain/bin/thor --network main --data-dir /opt/vechain/data --api-addr 0.0.0.0:8669 --verbosity 9 --max-peers 50 --cache 4096

/opt/vechain/bin/thor --version
Thor version 1.3.3-419e32e-release

<img width="1631" alt="2020-11-03 в 00 05 57" src="https://user-images.githubusercontent.com/37003941/97919690-474e0880-1d69-11eb-8e63-51678344e4d9.png">

**Comment by qianbin** [comment]
First we should know what causes the high CPU load. Is the node still synchronizing? Are there many http requests to this node?

**Comment by smithy9901** [comment]
Node is fully synchronized 
Request ~25/sec 
The long request looks like this
`/logs/event`

**Comment by qianbin** [comment]
> Node is fully synchronized
> Request ~25/sec
> The long request looks like this
> `/logs/event`

'/logs/event' is indeed a a time-costly operation. what are the parameters? need that to see if it can be optimized.
