### ISSUE TITLE
关于token交易手续费的问题

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#414]
以下是根据js sdk测算Gas改成Golang的算法。但是怎么感觉算出来的gas好像不太对。算出来的gas比最终的gasUsed还要少。这是什么原因呀？算法有问题吗。
```golang
func IntrinsicGas(clauses []vet.Clause) int {
	const txGas = 5000
	const clauseGas = 16000
	const clauseGasContractCreation = 48000

	if len(clauses) == 0 {
		return txGas + clauseGas
	}
	var sum int = txGas
	for _, c := range clauses {
		if c.To != "" {
			sum += clauseGas
		} else {
			sum += clauseGasContractCreation
		}
		sum += dataGas(c.Data)
	}
	return sum

}
func dataGas(data string) int {
	const zgas = 4
	const nzgas = 68

	var sum int = 0
	for i := 2; i < len(data); i += 2 {
		if data[i:i+2] == "00" {
			sum += zgas
		} else {
			sum += nzgas
		}
	}
	return sum
}
```

**Comment by libotony** [comment]
这个计算出来的的是固有gas,如果是调用合约的交易还会收取vm中消耗的手续费

**Comment by hzccc** [comment]
> 这个计算出来的的是固有gas,如果是调用合约的交易还会收取vm中消耗的手续费

这个vm消耗的手续费可以估算吗？我想要预测一下最终的手续费大概是多少。

**Comment by libotony** [comment]
`POST /accounts/*` 可以大致预估，一般推荐在预估的基础上增加15000

**Comment by qianbin** [comment]
> 以下是根据js sdk测算Gas改成Golang的算法。但是怎么感觉算出来的gas好像不太对。算出来的gas比最终的gasUsed还要少。这是什么原因呀？算法有问题吗。
> 
> ```go
> func IntrinsicGas(clauses []vet.Clause) int {
> 	const txGas = 5000
> 	const clauseGas = 16000
> 	const clauseGasContractCreation = 48000
> 
> 	if len(clauses) == 0 {
> 		return txGas + clauseGas
> 	}
> 	var sum int = txGas
> 	for _, c := range clauses {
> 		if c.To != "" {
> 			sum += clauseGas
> 		} else {
> 			sum += clauseGasContractCreation
> 		}
> 		sum += dataGas(c.Data)
> 	}
> 	return sum
> 
> }
> func dataGas(data string) int {
> 	const zgas = 4
> 	const nzgas = 68
> 
> 	var sum int = 0
> 	for i := 2; i < len(data); i += 2 {
> 		if data[i:i+2] == "00" {
> 			sum += zgas
> 		} else {
> 			sum += nzgas
> 		}
> 	}
> 	return sum
> }
> ```

这段逻辑在其实可以在这里找到 https://github.com/vechain/thor/blob/b13810f082da30cff505163d257c45e75d2ab115/tx/transaction.go#L338

**Comment by hzccc** [comment]
> `POST /accounts/*` 可以大致预估，一般推荐在预估的基础上增加15000

意思是我可以把未签名的原始交易调用这个接口来获取vm大致需要需要使用的gas
