### ISSUE TITLE
Building on linux/ARM64 fails

### ISSUE THREAD

**Issue by jaydp17** [vechain/thor#425]
## OS Version: 
linux/ARM64

## Commit hash : (if develop)
tags/v1.3.7
 
## Expected behavior
Build a binary for ARM64

## Actual behavior
Here's the error that pops up when building on ARM64
```
$ make thor

# github.com/ethereum/go-ethereum/crypto/bn256/cloudflare
../pkg/mod/github.com/ethereum/go-ethereum@v1.8.14/crypto/bn256/cloudflare/gfp_arm64.s:109: illegal or missing addressing mode for symbol R18
asm: assembly of ../pkg/mod/github.com/ethereum/go-ethereum@v1.8.14/crypto/bn256/cloudflare/gfp_arm64.s failed
make: *** [Makefile:18: thor] Error 2
```

## Steps to reproduce the behavior

Run `make thor` on linux/ARM64

## Further comments

This has been addressed in newer releases of go-ethereum https://github.com/ethereum/go-ethereum/pull/19183

**Comment by libotony** [comment]
hi @jaydp17, I have  made a pull request to solve this, you can pull source from https://github.com/libotony/thor/tree/arm64-bn256 to test it

**Comment by jaydp17** [comment]
Thanks @libotony for the fix, the build succeeds 🙌 
Ran it for about an hour w/o any problems
