### ISSUE TITLE
unnecessary repeated message when badTx and Rejected occurs during post new tx

### ISSUE THREAD

**Issue by libotony** [vechain/thor#43]
## OS Version: 
OSX 

## Commit hash : (if develop)

00e0c665e59b2476a587f788f783918b778e1104
 
## Expected behavior
Tell us what should happen.
`tx rejected: known tx`

## Actual behavior
Tell us what happens instead. Provide a log message if relevant.
`rejected tx: tx rejected: known tx`

## Steps to reproduce the behavior

post an known tx

**Comment by qianbin** [comment]
resolved by #45
