### ISSUE TITLE
“No Internet” error message 

### ISSUE THREAD

**Issue by theonion123** [vechain/thor#448]
Hi there,

I have down loaded the VeChainThor iOS app

## Expected behaviour
Should allow for withdrawal 

## Actual behaviour 
Gives error message “No internet access” and does not allow me to proceed with withdrawal

**Comment by theonion123** [comment]
If you need more information just let me know, haven’t been able to contact anyone else yet. Thanks

**Comment by bigmuxx8** [comment]
I’m currently having this same issue.
