### ISSUE TITLE
现在的交易手续费变了吗？不是原来的21个VTHO了？

### ISSUE THREAD

**Issue by hzccc** [vechain/thor#459]
疑问就是title。话说有QQ群或者微信群吗 想加一下有问题好问一下

**Comment by libotony** [comment]
baseGasPrice 改变了，详情请见https://twitter.com/vechainofficial/status/1381608086629048331，微信群 @mongelly

**Comment by mongelly** [comment]
@hzccc 可以扫码这个微信加入我们的技术社区微信群
![image](https://user-images.githubusercontent.com/11418670/116498233-df254d00-a8db-11eb-9d56-3357c22a0b3e.png)

**Comment by hzccc** [comment]
> @hzccc 可以扫码这个微信加入我们的技术社区微信群
> ![image](https://user-images.githubusercontent.com/11418670/116498233-df254d00-a8db-11eb-9d56-3357c22a0b3e.png)

已加

**Comment by harryweiyongjie** [comment]
> @hzccc 可以扫码这个微信加入我们的技术社区微信群 ![image](https://user-images.githubusercontent.com/11418670/116498233-df254d00-a8db-11eb-9d56-3357c22a0b3e.png)

现在还可以加吗
