### ISSUE TITLE
Fee estimation fails with "insufficient balance for transfer" for values greater than `1f1f9313e3bea01a4000`

### ISSUE THREAD

**Issue by futpib** [vechain/thor#460]
## OS Version: 
Linux 
 
## Expected behavior

Request:
```bash
curl 'https://thor.vechain.example.com/accounts/*?revision=best' --data-raw '{"clauses":[{"to":"0xa7a0E1EFd1a2f9F70547eAd5e2b5c429D5d84ba2","value":"0x1f1f9313e3bea01a4001","data":"0x"}]}'
```

Response:
```json
[
  {
    "data": "0x",
    "events": [],
    "transfers": [
      {
        "sender": "0x0000000000000000000000000000000000000000",
        "recipient": "0xa7a0e1efd1a2f9f70547ead5e2b5c429d5d84ba2",
        "amount": "0x1f1f9313e3bea01a4001"
      }
    ],
    "gasUsed": 0,
    "reverted": false,
    "vmError": ""
  }
]
```

## Actual behavior

Request:
```bash
curl 'https://thor.vechain.example.com/accounts/*?revision=best' --data-raw '{"clauses":[{"to":"0xa7a0E1EFd1a2f9F70547eAd5e2b5c429D5d84ba2","value":"0x1f1f9313e3bea01a4001","data":"0x"}]}'
```

Response:
```json
[
  {
    "data": "0x",
    "events": [],
    "transfers": [],
    "gasUsed": 0,
    "reverted": true,
    "vmError": "insufficient balance for transfer"
  }
]
```

## Steps to reproduce the behavior
Run the requests above on a running vechain/thor instance.

Note that running this with `value` `0x1f1f9313e3bea01a4000` or lower does work as expected.

**Comment by qianbin** [comment]
the 'caller' field which stands for msg sender is missing. the balance of 'caller' is required to be greater or equal to transfer amount.

**Comment by futpib** [comment]
Why is `caller` not required for `value` of `0x1f1f9313e3bea01a4000` or lower and is required for value of `0x1f1f9313e3bea01a4001` or greater?

**Comment by libotony** [comment]
The caller will be `0x0000000000000000000000000000000000000000` if it's missing in the request body, and the balance of `0x0000000000000000000000000000000000000000` is `0x1f1f9313e3bea01a4000`
