### ISSUE TITLE
Inconsistent hex values in bloom filters

### ISSUE THREAD

**Issue by daithihearn** [vechain/thor#477]
Hi there,

I have noticed that some hex values in the bloom filter contain the 0x prefix and others do not. The upshot of this is that I need to check twice. This is less efficient and will probably result in more fause positives.

kind regards,
Daithi

**Comment by qianbin** [comment]
the contents added in to bloom filter are all byte slices. what does 0x prefix mean?

**Comment by Jaysonmaldx** [comment]
Ok

**Comment by darrenvechain** [comment]
Closing as it's marked as stale and without activity
