### ISSUE TITLE
VET Token Swap Service Unresponsive/Error -  iOS & Android

### ISSUE THREAD

**Issue by jcjc1223** [vechain/thor#491]
Hi guys,

I am having issues with the VET Token Swap Service. I have created new wallets on both iOS and Android versions of the App, however when I go to start the Token Swap, I cannot get past the wallet selection screen.

On Android, after I select the wallet and hit confirm, a spinning loading circle will appear for about 20 seconds, and then disappear. The app does not progress to the next stage. No error messages appear.

On iOS, after I select the wallet and hit confirm, the same thing happens however the "No Internet Access" error appears. I do have access to the internet.

Is anyone able to assist? I assume the Token Swap Service is still live and working?

Thank you in advance!

JC
![Screenshot_20210908-090820_4](https://user-images.githubusercontent.com/90315793/132487166-25bdb8a3-5332-4139-972c-4e26b560283b.jpg)
![unnamed](https://user-images.githubusercontent.com/90315793/132487176-601c32ff-9578-4371-8aa5-1a5b2ea13188.jpg)

**Comment by XJWX89** [comment]
hi @jcjc1223, please contact support@vechain.com for further assistance
