### ISSUE TITLE
Websocket subscriptions for event logs

### ISSUE THREAD

**Issue by hplar** [vechain/thor#494]
https://docs.vechain.org/thor/get-started/api.html#get-subscriptions-event

I was wondering if anyone could add to the docs an example of how to subscribe to events?

Currently I'm polling the logs/events endpoint to fetch events, but I would love to try to use the subscription endpoint.
The problem is, I'm not sure how to connect properly (from either typescript/javascript/node or python) and send the required request as specified in the docs.

Cheers,
Ralph

**Comment by qianbin** [comment]
It's required to establish a WebSocket connection via the url like `ws://127.0.0.1:8669/subscriptions/event`.

**Comment by hplar** [comment]
> It's required to establish a WebSocket connection via the url like `ws://127.0.0.1:8669/subscriptions/event`, or over TLS `wss://some-domain/subscriptions/event`.

Hi Qianbin, thanks for your reply. 

What do I do after the connection has been established, to subscribe to a topic? Do I send the parameters as a JSON ws-message to the endpoint? Or should I provide the parameters in the request when establishing the connection?

**Comment by qianbin** [comment]
> > It's required to establish a WebSocket connection via the url like `ws://127.0.0.1:8669/subscriptions/event`, or over TLS `wss://some-domain/subscriptions/event`.
> 
> Hi Qianbin, thanks for your reply.
> 
> What do I do after the connection has been established, to subscribe to a topic? Do I send the parameters as a JSON ws-message to the endpoint? Or should I provide the parameters in the request when establishing the connection?

No need to send message via ws connection. And yes, params are passed in query string.

**Comment by hplar** [comment]
That helped! 

Closing the issue and thank you for your time.
