### ISSUE TITLE
les contenus ajoutés dans le filtre bloom sont tous des tranches d'octets. que signifie le préfixe 0x

### ISSUE THREAD

**Issue by taszipame65** [vechain/thor#503]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
Windows/
## Expected behavior
Tell us what should happen.

## Actual behavior
Tell us what happens instead. Provide a log message if relevant.

**Comment by darrenvechain** [comment]
Closing as it's marked as stale and without activity
