### ISSUE TITLE
发送代币交易失败

### ISSUE THREAD

**Issue by harryweiyongjie** [vechain/thor#505]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
Linux

同一个代币，别人转给我成功了，我转出去一直失败，不知道哪里出了问题，看了交易收据也没看出问题。我自己转出的永远就是revert
**成功的交易**：https://explore.vechain.org/transactions/0x50ae46c825aff1b49097b73854ae2515538c1767e84d9c738b678cb0c2da46d4#info
**revert的交易**
https://explore.vechain.org/transactions/0xdf458041b0bf1fe584da6956d1f68e42b3077d30ada585c2c1f7031cb9a5fc3f#info

**Comment by libotony** [comment]
HAI代币的Decimal是8

**Comment by harryweiyongjie** [comment]
> HAI代币的Decimal是8

谢谢，成功了
