### ISSUE TITLE
CORS: Error Response Headers without access-control-allow-origin: *

### ISSUE THREAD

**Issue by NikitaIT** [vechain/thor#532]
Swagger show CORS error instead of Error 400.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/16810067/172634626-99e2c83c-90bc-463d-b557-7f1ba4396729.png">

## OS Version: 
Chrome

## Expected behavior

```
curl -X 'GET' \
  'https://testnet.veblocks.net/accounts/015034aa590125b64023a0262112b98d72e3c8e40e' \
  -H 'accept: application/json'
```

```diff
access-control-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,x-genesis-id
access-control-allow-methods: GET, POST, OPTIONS, HEAD
+ access-control-allow-origin: *
access-control-expose-headers: x-genesis-id,x-thorest-ver
access-control-max-age: 86400
...
```

## Actual behavior

Errors without access-control-allow-origin: *

### Ok
```
curl -X 'GET' \
  'https://testnet.veblocks.net/accounts/0x5034aa590125b64023a0262112b98d72e3c8e40e' \
  -H 'accept: application/json'
```

```diff
access-control-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,x-genesis-id
access-control-allow-methods: GET, POST, OPTIONS, HEAD
access-control-allow-origin: *
access-control-expose-headers: x-genesis-id,x-thorest-ver
access-control-max-age: 86400
...
```
### Error 400: address: invalid prefix

```
curl -X 'GET' \
  'https://testnet.veblocks.net/accounts/015034aa590125b64023a0262112b98d72e3c8e40e' \
  -H 'accept: application/json'
```

```diff
access-control-allow-headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,x-genesis-id
access-control-allow-methods: GET, POST, OPTIONS, HEAD
access-control-expose-headers: x-genesis-id,x-thorest-ver
access-control-max-age: 86400
...
```

## Steps to reproduce the behavior

Go to https://testnet.veblocks.net/accounts/015034aa590125b64023a0262112b98d72e3c8e40e

**Comment by libotony** [comment]
I think this may not be the issue of CORS config. The error is `Error 400: address: invalid prefix`, check the address you provided.

**Comment by NikitaIT** [comment]
@libotony I checked the errors returned by the API. And in the case of a valid request(`0x5034aa590125b64023a0262112b98d72e3c8e40e`), everything works fine as I indicated above. But if the request result is error (`address: invalid prefix`), then there is no CORS header in it.

**Comment by NikitaIT** [comment]
In my case, I want to extend the Swagger config to generate the client correctly. This requires a bit of config tweaking. But I can't test it quickly without proxy due to CORS.
```
responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Error
          content:
            text/plain:
              schema:
                format: 'ValidationError'
                type: string
```

**Comment by libotony** [comment]
Sorry, I just got your point. You need `access-control-allow-origin` to present even if it's a bad request right?

**Comment by NikitaIT** [comment]
@libotony yes

**Comment by libotony** [comment]
I'll look into that.

**Comment by libotony** [comment]
@NikitaIT I have tested locally, thor returns `access-control-allow-origin` header when it's 400, it might be the configuration of `testnet.veblocks.net`. You can try `https://vethor-node-test.vechaindev.com` instead. I'll talk to the admin of veblocks about this.

**Comment by Livadminsupport** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by libotony** [comment]
@NikitaIT The admin of veblocks has fixed the issue.
