### ISSUE TITLE
Deployed contract does not match the predicted address

### ISSUE THREAD

**Issue by iliya-hajjar** [vechain/thor#555]
Hi,
We've built multiple dapps over ethereum-like networks that require some control over created contracts addresses.
normally, in EVM the contract address is generated using following code:

`contractAddr = crypto.CreateAddress(caller.Address(), nonce)`

However, in your version of EVM the contractAddress is generated in runtime:

`contractAddr = evm.NewContractAddress(evm, evm.contractCreationCount)`

this completely prevents us from migrating and supporting your network in our dapps.
Will there be any updates in this regard? any hopes? any work-arounds?

Cheers,

**Comment by sh-ebrahimi** [comment]
Yeah,
I know that the nonces supposed to be random but if we at least get any controls over this issue, we can handle our nonces locally to finally support vechain.

**Comment by libotony** [comment]
For `CREATE` you can calculate contract address before sending tx, take a look at
https://github.com/vechain/thor/blob/bee753fedf8e169e248b04d65eb37555b30b34d3/thor/address.go#L107-L112
you need `txID`, `clauseIndex` and `creationCount`. Regarding the  `creationCount`, it's the overall contract creation count for one clause, so if you send a tx with one clause `{to: null, data: <creation code>}` then it should be 1.
To generate the address you wanted, you need to change nonce in the tx then txID is generated and  you will get contract address. Regarding `nonce` it a random number in tx which is different from ethereum's account nocne.

**Comment by libotony** [comment]
https://github.com/vechain/thor/blob/bee753fedf8e169e248b04d65eb37555b30b34d3/vm/patch.go#L19-L20

`CREATE2` is also available.

**Comment by aghamir** [comment]
Dear @libotony,

Thanks kindly for your response.

>  Regarding the `creationCount`, it's the overall contract creation count for one clause, so if you send a tx with one clause `{to: null, data: <creation code>}` then it should be 1.

We need to reach the exact same contract address in `CREATE` due to the fact that we provide exchanges wallet contract(unless the same user address will not accessible in Vechain network and causes fund loss in recovery plans). However, the minimum amount of `creationCount` is 1 in your solution and our generated mother contract address has nonce on 0. 

`CREATE2` is OK, however, we must first deploy the same address mother with `CREATE` in Vechain.

Do you have any solution for nonce 0?

Regards,

**Comment by libotony** [comment]
We have a different tx-model than Ethereum. Take a look at the function signature:

``` go
// Ethereum
func CreateAddress(caller common.Address, nonce uint64) Address
// VeChain
func CreateContractAddress(txID Bytes32, clauseIndex uint32, creationCount uint32) Address
```

Regardless of the `creationCount`, you might not be able to create the same contract address using the same method of Ethereum.

And I took another look into the source code, `creationCount` starts from 0.

**Comment by libotony** [comment]
@aghamir I am afraid this is can not be done, sorry for the inconvenience. Closing this issue, feel free to reopen or append comments.
