### ISSUE TITLE
hackenproof

### ISSUE THREAD

**Issue by 0x34d** [vechain/thor#566]
Is this [Program](https://hackenproof.com/vechain) dead?

**Comment by libotony** [comment]
Unfortunately, this project has been discontinued.

**Comment by libotony** [comment]
@0x34d Apologies for the wrong information I replied above, the program is live and I found the right person to contact.

**Comment by 0x34d** [comment]
> @0x34d Apologies for the wrong information I replied above, the program is live and I found the right person to contact.

Did you know, I did a blunder based on your information?

**Comment by libotony** [comment]
> > @0x34d Apologies for the wrong information I replied above, the program is live and I found the right person to contact.
> 
> Did you know, I did a blunder based on your information?

Sorry to hear that, let me know what I can do to help.

**Comment by 0x34d** [comment]
yes, I public my fuzzing harness suite, https://github.com/vechain/thor/pull/567

**Comment by libotony** [comment]
> yes, I public my fuzzing harness suite, #567

I am in contact with hacken team and they will come back to you soon.

**Comment by libotony** [comment]
If you don't mind I am going to raise a PR to fix #569. Thank you for your report!

**Comment by 0x34d** [comment]
Alright, thanks.

**Comment by libotony** [comment]
Hi @0x34d we have got the invoices from hacken team, it's in the middle of our internal process, I'll see what I can do.
