### ISSUE TITLE
Error when compiling the code

### ISSUE THREAD

**Issue by yuxiaobo96** [vechain/thor#572]
/bug
master branch
When compiling the code according to README.md, an error is reported:
![image](https://user-images.githubusercontent.com/41496192/227871798-215aa4e2-17f0-4199-8ac9-b61194c71ec7.png)

What is the reason for this?

**Comment by libotony** [comment]
Looks like cgo is disabled, could you try `CGO_ENABLED=1 make`?

**Comment by yuxiaobo96** [comment]
Thank you, solved
