### ISSUE TITLE
Unknown error while creating custom network

### ISSUE THREAD

**Issue by yuxiaobo96** [vechain/thor#573]
When creating a custom network, the official provides an example: [genesis/example.json](https://raw.githubusercontent.com/vechain/thor/master/genesis/example.json).

Currently we have two master node addresses: 0xe7f5335755f87b46ce5730f90b922a129e2b3eaa, 0x4bfd7a7330060cb32102030b5b0aa90d6a2803e7

After executing the ./thor --network ../genesis/genesis.json --data-dir /home/data command, it has been stuck, as follows:

![image](https://user-images.githubusercontent.com/41496192/228469128-44d41cfa-e37e-4b15-b9af-49c989c1926b.png)

It doesn't print an error. Is this because of a problem with the genesis.json configuration, or something else?

**Comment by libotony** [comment]
The two master nodes need to connect to each other. https://docs.vechain.org/thor/get-started/custom-network#custom-bootnode

**Comment by yuxiaobo96** [comment]
I don't understand how the master nodes are connected to each other? Does it depend on the genesis.json file?

**Comment by libotony** [comment]
The node is waiting for synchronization, they need to be connected via peer to peer network to sync, or for masters to propose new blocks.

**Comment by libotony** [comment]
> Does it depend on the genesis.json file?
The genesis file seems fine.

**Comment by yuxiaobo96** [comment]
I've set up a custom network.
How to configure browser in custom network?

**Comment by libotony** [comment]
Take a look at https://github.com/vechain/insight-app

**Comment by yuxiaobo96** [comment]
After installing insight-app on the master node and running it, the network can only choose the main network and test network. How to add the custom network to the browser?
As shown below:
![1680141885597](https://user-images.githubusercontent.com/41496192/228709321-e23a964a-9aaf-4e5b-9953-3b6c3511f391.png)

**Comment by libotony** [comment]
Add your custom node in [sync](https://env.vechain.org/) by this [guide](https://env.vechain.org/) then open https://insight.vecha.in in sync  would work

**Comment by libotony** [comment]
Is the original topic `custom network no new block produced` solved?

**Comment by yuxiaobo96** [comment]
already solved
