### ISSUE TITLE
Support ARM based architectures such as Amazon EC2 Graviton2 CPUs

### ISSUE THREAD

**Issue by kgapos** [vechain/thor#574]
Given the strong focus of vechain on sustainability, I think it makes sense that you add docker support running nodes on energy efficient ARM based architectures, such as [Amazon EC2 Graviton2 CPUs](https://aws.amazon.com/ec2/graviton/). There are [Graviton EC2 instances that are optimized for IO](https://aws.amazon.com/ec2/instance-types/i4g/), making them excellent platforms for our nodes. These instances come with a >60% reduction in energy consumption and a corresponding reduction on the already excellent carbon footprint of AWS, [over 95% renewable in Ireland and some other regions](https://sustainability.aboutamazon.com/environment/the-cloud?energyType=true).

You currently publish docker containers only for `linux/amd64`. Therefore, we will need to build a new docker image that targets the ARM architecture. I think [Graviton2 needs `linux/arm64/8`](https://aws.amazon.com/blogs/containers/how-to-build-your-containers-for-arm-and-save-with-graviton-and-spot-instances-on-amazon-ecs/) but please confirm this.

I can implement this on my own, but I think there is value in offering this option in [the official vechain docker hub registry](https://hub.docker.com/r/vechain/thor/tags), so that others may quickly and easily optimize their energy efficiency and reduce their carbon footprint.

## Expected behavior
I should be able to run the vechain node on ARM based architectures such as Amazon EC2 Graviton2 CPUs. 

## Actual behavior
According to [vechain docker hub](https://hub.docker.com/u/vechain), only `linux/amd64` is supported.

**Comment by libotony** [comment]
The current codebase supports ARM-based OSs. We need to add ARM-based docker images in the publishing process, I am exploring adding the GitHub registry as a secondary docker registry, will do it then. Thanks!

**Comment by libotony** [comment]
Hi @kgapos, please take a look at #577 `linux/arm64` has been added.

**Comment by kgapos** [comment]
Awesome, looking forward to the next release!
