### ISSUE TITLE
How to set the URL of a custom node

### ISSUE THREAD

**Issue by yuxiaobo96** [vechain/thor#576]
After downloading the sync client, when adding a custom node in the settings, what should be filled in the URL and what conditions need to be met?
![image](https://user-images.githubusercontent.com/41496192/229085269-acb3a7fc-2fe0-4b7b-b575-01d676640e83.png)

**Comment by libotony** [comment]
Add `--api-cors "file://"` to the API Node

**Comment by yuxiaobo96** [comment]
After using the --api command, the new host domain name is resolved. This master node is in the local area network and cannot be accessed from the external network. Is there any impact?
![image](https://user-images.githubusercontent.com/41496192/229405793-4aab9da7-bf0a-4e29-9b6e-102c6d205a71.png)

**Comment by libotony** [comment]
Keep the CORS settings as `--api-cors "file://" `

**Comment by yuxiaobo96** [comment]
THK.

**Comment by yuxiaobo96** [comment]
After the custom node is added successfully, the custom network cannot be selected in the upper right corner of explore, and the main page cannot be displayed?
![image](https://user-images.githubusercontent.com/41496192/229708169-b41fbfc7-c821-4e4c-8bc7-b15c9a51c355.png)

**Comment by libotony** [comment]
It's a centralized explorer, custom network is not supported. Try https://insight.vecha.in

**Comment by 63669733** [comment]
> It's a centralized explorer, custom network is not supported. Try https://insight.vecha.in

你好，请问自定义的网络，我们现在已经在同步区块了，现在想使用区块浏览器，要用哪个项目？Try https://insight.vecha.in/ 这个怎么用？

**Comment by libotony** [comment]
See https://github.com/vechain/thor/issues/573#issuecomment-1489586907

**Comment by 63669733** [comment]
![image](https://user-images.githubusercontent.com/12948697/229718038-98519097-df00-476f-b4df-b36082e5a514.png)
![image](https://user-images.githubusercontent.com/12948697/229718252-4970dd5f-83c0-45e9-873a-a077c4555f6c.png)
![image](https://user-images.githubusercontent.com/12948697/229718105-cd91b038-8ec3-454b-8da9-86064dce8e63.png)
做了这个修改，不能展示数据，是不是您说的eep the CORS settings as --api-cors "file://"  这个设置，我很不明白 --api-cors要怎么设置，file ？

**Comment by 63669733** [comment]
![image](https://user-images.githubusercontent.com/12948697/229720262-d7c4dd45-9122-4f0d-ae20-c0127894a245.png)
./thor --network ../genesis/genesis.json --data-dir /home/data --api-cors "*" --api-addr 192.168.1.40:8669
我用的这个命令启动的，可以看到接口可以跨域了，但是页面还是没展示出来，请问怎么弄

**Comment by libotony** [comment]
Add your custom node in [sync](https://env.vechain.org/) by this [guide](https://env.vechain.org/) then open https://insight.vecha.in/ in sync would work

> ./thor --network ../genesis/genesis.json --data-dir /home/data --api-cors "*" --api-addr 192.168.1.40:8669 我用的这个命令启动的，可以看到接口可以跨域了，但是页面还是没展示出来，请问怎么弄 @libotony

不要修改源码，直接在sync里边打开即可。
Do not edit the code, open https://insight.vecha.in/ in sync

**Comment by 63669733** [comment]
Done. Thank you.
