### ISSUE TITLE
Why not delete the deleted leaves but put empty values?

### ISSUE THREAD

**Issue by jongrun** [vechain/thor#580]
https://github.com/vechain/thor/blob/6aa5f94a1e379662931dd153e577fcc17239c56b/muxdb/internal/trie/leaf_bank.go#L205-L206
Why not delete the deleted leaves but put empty values?

**Comment by qianbin** [comment]
If the leaf is simply deleted, later query will get errNotFound, which means the leaf never appears. In rare case, e.g. 

* state A was set somewhen
* state A was deleted at block N
* leafbank updated to block N+M
* state A was set again at block N+M+X

Now if to query state A via `fastLeafGet` method, it will give nil result (looks like A never appears, unexpectedly).

**Comment by jongrun** [comment]
I read the codes about handling deleted leaves and never-seen leaves:
- never seen:
https://github.com/vechain/thor/blob/6aa5f94a1e379662931dd153e577fcc17239c56b/muxdb/internal/trie/leaf_bank.go#L93-L98
- deleted:
https://github.com/vechain/thor/blob/6aa5f94a1e379662931dd153e577fcc17239c56b/muxdb/internal/trie/trie.go#L228-L231

Now I get that:
- If the leaf can't be determined (deleted), we will read it from Hist and then Deduped trie.
- If the leaf is never seen, we can short-circuit and don't need to read from tries.

Therefore, the purpose of putting empty value is only for short circuit?
If we delete the leaves (instead of putting empty values), we can also determine the leaves correctly by reading it from Hist and then Deduped trie. The only shortcoming is that we can't short-circuit if the leaf is never-seen (because we can't distinguish never-seen or deleted).

My point is that, if the leaf bank only grows and is never pruned, is it scalable?
Is it worth the loss of scalability just for short-circuiting?

**Comment by jongrun** [comment]
> > Therefore, the purpose of putting empty value is only for short circuit? If we delete the leaves (instead of putting empty values), we can also determine the leaves correctly by reading it from Hist and then Deduped trie. The only shortcoming is that we can't short-circuit if the leaf is never-seen (because we can't distinguish never-seen or deleted).
> 
> It's important to short-circuit never-seens. This a related DoS attack case: https://hackmd.io/@iwck0wkoSzauVnsYI0h7JA/SkyFmk4_r
> 
> > My point is that, if the leaf bank only grows and is never pruned, is it scalable? Is it worth the loss of scalability just for short-circuiting?
> 
> Trie nodes can be pruned, but leaves can't I think.

The DoS attack is about transactions, but it is imposible to hit the nodes in leaf bank during a transaction execution because the executing block number must be greater than steady number.

**Comment by qianbin** [comment]
> The DoS attack is about transactions, but it is imposible to hit the nodes in leaf bank during a transaction execution because the executing block number must be greater than steady number.

There's no difference between txs and calling code. The attack vector randomly access accounts, which most likely do not exist. Without leaf bank, each OP_BALANCE produces log(count of account) node queries. With leaf bank, the complexity of account/state access is reduced from O(log(n)) to O(1), where n is the number of accounts.

**Comment by qianbin** [comment]
And `executing block number must be greater than steady number` is not important. Remember that a node's commit number is always less than or equal to its parent's.

**Comment by jongrun** [comment]
> > The DoS attack is about transactions, but it is imposible to hit the nodes in leaf bank during a transaction execution because the executing block number must be greater than steady number.
> 
> There's no difference between txs and calling code. The attack vector randomly access accounts, which most likely do not exist. Without leaf bank, each OP_BALANCE produces log(count of account) node queries. With leaf bank, the complexity of account/state access is reduced from O(log(n)) to O(1), where n is the number of accounts.

I means that the DoS attack is mainly about transactions. The query APIs (like eth_call) may suffer from O(log(n)) complexity but it is not the key factor of the DoS attack.

**Comment by jongrun** [comment]
> it is imposible to hit the nodes in leaf bank during a transaction execution

Do you mean that it is posible to hit the nodes in leaf bank during a transaction execution?

**Comment by jongrun** [comment]
> Remember that a node's commit number is always less than or equal to its parent's.

Yes, it is. But what's the point of this?

**Comment by qianbin** [comment]
> I means that the DoS attack is mainly about transactions. The query APIs (like eth_call) may suffer from O(log(n)) complexity but it is not the key factor of the DoS attack.

Got it. Network, not a single node.


> Do you mean that it is posible to hit the nodes in leaf bank during a transaction execution?

Yes. (leaf value in leaf bank)

**Comment by qianbin** [comment]
> Yes, it is. But what's the point of this?

Txs in new block can hit the leaf value in leaf bank.

**Comment by jongrun** [comment]
> Txs in new block can hit the leaf value in leaf bank.
Sorry, I can't understand it. Doesn't the nodeCommitNum represent the leaf's root commit number?
https://github.com/vechain/thor/blob/6aa5f94a1e379662931dd153e577fcc17239c56b/muxdb/internal/trie/trie.go#L216-L220

**Comment by jongrun** [comment]
> > Txs in new block can hit the leaf value in leaf bank.
> 
> Sorry, I can't understand it. Doesn't the nodeCommitNum represent the leaf's root commit number?
> 
> https://github.com/vechain/thor/blob/6aa5f94a1e379662931dd153e577fcc17239c56b/muxdb/internal/trie/trie.go#L216-L220

Oh, I see. The leaf's root node is not the root of account trie but the storage trie. The root of storage trie may be less than steady number.

**Comment by qianbin** [comment]
> So if we get balance of an account (access the account trie), we can't hit leaf bank, right?

Yes, you can. Think about the account A which is not recently modified, linked by trie nodes N0->N1->N2->...->ACC, where N0 is the root node. The commit num of N0 should > `steadyCommitNum`, so goes to N1, N2... until we find that Nn's commit num is smaller than `steadyCommitNum`, then leaf bank is usable.

**Comment by jongrun** [comment]
> > So if we get balance of an account (access the account trie), we can't hit leaf bank, right?
> 
> Yes, you can. Think about the account A which is not recently modified, linked by trie nodes N0->N1->N2->...->ACC, where N0 is the root node. The commit num of N0 should > `steadyCommitNum`, so goes to N1, N2... until we find that Nn's commit num is smaller than `steadyCommitNum`, then leaf bank is usable.

Got it. Before hit the leaf bank, we may iterate some intermediate nodes but not all.

**Comment by jongrun** [comment]
> If the leaf is simply deleted, later query will get errNotFound, which means the leaf never appears. In rare case, e.g.
> 
> * state A was set somewhen
> * state A was deleted at block N
> * leafbank updated to block N+M
> * state A was set again at block N+M+X
> 
> Now if to query state A via `fastLeafGet` method, it will give nil result (looks like A never appears, unexpectedly).

For the example, if state A was set again at block N+M+X, it is imposible to hit the leaf bank of block N+M, isn't it?

**Comment by qianbin** [comment]
> For the example, if state A was set again at block N+M+X, it is imposible to hit the leaf bank of block N+M, isn't it?

Right.

**Comment by jongrun** [comment]
If a account selfdestruct in a target block, the corresponding leaf node in the account trie can be deleted(marked as undetermined) in leaf bank, but the leaf nodes of the storage trie of the account can't be deleted. This will not cause safety problem but make the leaf bank unclean. Is it right?

**Comment by qianbin** [comment]
> If a account selfdestruct in a target block, the corresponding leaf node in the account trie can be deleted(marked as undetermined) in leaf bank, but the leaf nodes of the storage trie of the account can't be deleted. This will not cause safety problem but make the leaf bank unclean. Is it right?

Right. Comparing to intermediate nodes, leaves are not the problem.
