### ISSUE TITLE
Is it possible that use the key of a leaf value as the leaf's path?

### ISSUE THREAD

**Issue by jongrun** [vechain/thor#581]
https://github.com/vechain/thor/blob/6aa5f94a1e379662931dd153e577fcc17239c56b/muxdb/internal/trie/trie.go#L214-L219
The leaf bank only stores the leaves of a trie in blockNum which is less than steadyNum. However, in most cases, user query a state of 
a block whose number is greater than steadyNum, e.g., get balance of an account in a recent height (like LastHeight-2). So the leaves can't be hit in the happy path.

Is it possible that, in any tries with path-based store-keys, we use the key of a leaf value as the leaf's path. If so, we can get a leaf with key of its value directly instead of resolving intermediate nodes. But the path definition of a leaf will be inconsistent with a intermediate node, so extra complexity is introduced.

**Comment by qianbin** [comment]
> a block whose number is greater than steadyNum, e.g., get balance of an account in a recent height (like LastHeight-2). So the leaves can't be hit in the happy path.

It's not a problem. If the account is recently modified, it's all related account trie nodes will hit in cache with high probability.

> Is it possible that, in any tries with path-based store-keys, we use the key of a leaf value as the leaf's path. If so, we can get a leaf with key of its value directly instead of resolving intermediate nodes. But the path definition of a leaf will be inconsistent with an intermediate node, so extra complexity is introduced.

The key of a leaf value is the same as leaf's path?

**Comment by jongrun** [comment]
> The key of a leaf value is the same as leaf's path?

The key of a leaf value is account address for account tries, slot position for storage tries.

**Comment by jongrun** [comment]
> The key of a leaf value is the same as leaf's path?

The key of a leaf value is account address for account tries, slot position for storage tries. If we set the leaf path = the key of a leaf value, we can get a state directly by one IO. And so we can get rid of the extra storage of leaf bank.

**Comment by qianbin** [comment]
> The key of a leaf value is account address for account tries, slot position for storage tries. If we set the leaf path = the key of a leaf value, we can get a state directly by one IO. And so we can get rid of the extra storage of leaf bank.

Sounds interesting. It's worth to do further work on it, but i think it's not easy.
