### ISSUE TITLE
What's the benefit of using xxx+name+path instead of xxx+nodeHash as store-key?

### ISSUE THREAD

**Issue by jongrun** [vechain/thor#582]
https://github.com/vechain/thor/blob/6aa5f94a1e379662931dd153e577fcc17239c56b/muxdb/internal/trie/trie.go#L83-L92
- For name, it can avoid to share nodes among storage tries. But what's the purpose?
- For path, I thought it is for fast iterative but it seems that we can't gain any iterative acceleration because of the commitNum prefix. So what's the benefit of it?

**Comment by qianbin** [comment]
Use the node hash to index the node is stupid. It's a disaster for the underlying LSM DB, endless table compaction and huge write amplification. To 

> * For name, I think it is to avoid deletion-conflict of different accounts' storage in leaf bank. Is there any other purpose?

Yes, it's to isolate tries, so it's safe to mange leaf bank and prune tries.

> * For path, I thought it is for fast iterative but it seems that we can't gain any iterative acceleration because of the commitNum prefix. So what's the benefit of it?

The prefix is partition ID (commitNum/t.back.HistPtnFactor), not commitNum

benefits:

* node iteration is fast enough (faster with larger HistPtnFactor)
* LSM DB friendly (more friendly with smaller HistPtnFactor)

**Comment by jongrun** [comment]
I got it.
The path is for LSM DB friendly. And Once we use path instead of hash, the name is necessary to isolate tries.
For node iteration, I have some confusion. How can we iterate all nodes of a account trie efficiently?

**Comment by qianbin** [comment]
> The path is for LSM DB friendly. And Once we use path instead of hash, the name is necessary to isolate tries.

Not only the path, but the partition ID. Yes, the name is important.

> For node iteration, I have some confusion. How can we iterate all nodes of an account trie efficiently?

It's already much much faster than using node hash as key, and is never the bottle neck.

In this project, there's no case to iterate all nodes of a trie, but a part of them, by passing `baseCommitNum` to `trie.NodeIterator`.

**Comment by jongrun** [comment]
> The prefix is partition ID (commitNum/t.back.HistPtnFactor), not commitNum
> 
> benefits:
> 
> * node iteration is fast enough (faster with larger HistPtnFactor)
> * LSM DB friendly (more friendly with smaller HistPtnFactor)

How the partition ID take effect? And what's the classic configuration value for HistPtnFactor or DedupedPtnFactor.

**Comment by jongrun** [comment]
> In this project, there's no case to iterate all nodes of a trie

There is no case to fast sync?

**Comment by qianbin** [comment]
> How the partition ID take effect? And what's the classic configuration value for HistPtnFactor or DedupedPtnFactor.

It'll be the prefix of node key and it orders nodes from old to new, to significantly reduce db's table compaction and write amplification. 

The value for HistPtnFactor/DedupedPtnFactor depends on the chain scale and block time. It has to be determined by real env test.

> There is no case to fast sync?

No. Full sync is acceptable for now.

**Comment by jongrun** [comment]
> It'll be the prefix of node key and it orders nodes from old to new, to significantly reduce db's table compaction and write amplification.

What's the different between using partition ID and block number?

**Comment by qianbin** [comment]
> What's the different between using partition ID and block number?

The purpose of partition (and the suffix `commitNum%t.back.HistPtnFactor`) is to make the nodes better compressed. If you're familiar with trie nodes encoding, you can find the secret in this code snippet https://gist.github.com/qianbin/bffcd248b7312c35d7d526a974018b1b

By introducing partition, the full-archived node saves at least 50% disk space.

**Comment by jongrun** [comment]
> make the nodes better compressed

Got it. That can make some nodes (for near blocks) have the same prefix partitionID+path, which is better for compressing.

> * LSM DB friendly (more friendly with smaller HistPtnFactor)

Why it is more LSM DB friendly with smaller HistPtnFactor?

**Comment by qianbin** [comment]
> Why it is more LSM DB friendly with smaller HistPtnFactor?

Less table compaction, leads to higher DB write throughput. It'll be perfect if set HistPtnFactor to 1, but would lose the benefit of compression.

**Comment by jongrun** [comment]
> Using the node hash to index the node is stupid. It's a disaster for the underlying LSM DB, endless table compaction and huge write amplification.

Why do you say the hash-based store scheme has huge write amplification.

**Comment by qianbin** [comment]
> Why do you say the hash-based store scheme has huge write amplification.

Hash-based keys is totally random. According to leveldb's spec, one table contains random keys will almost overlaps with all next-level tables, which causes high write amp. One word to way, keys in order are much better.

**Comment by jongrun** [comment]
> The purpose of partition (and the suffix `commitNum%t.back.HistPtnFactor`) is to make the nodes better compressed. If you're familiar with trie nodes encoding, you can find the secret in this code snippet https://gist.github.com/qianbin/bffcd248b7312c35d7d526a974018b1b
> 
> By introducing partition, the full-archived node saves at least 50% disk space.

I misunderstood your point. I thought your compression is for leveldb, but it seems that you mean rlp-encoding compression. How can the partition ID in key (which is not included in node) influence the node encoding?

**Comment by qianbin** [comment]
> I misunderstood your point. I thought your compression is for leveldb, but it seems that you mean rlp-encoding compression. How can the partition ID in key (which is not included in node) influence the node encoding

it’s for leveldb.

**Comment by jongrun** [comment]
> it’s for leveldb.
What's your point to refer nodes encoding and the code sinppet.

**Comment by qianbin** [comment]
> What's your point to refer nodes encoding and the code sinppet?

I'm trying to explain why partition brings the benefits of db compression.

**Comment by jongrun** [comment]
> Using the node hash to index the node is stupid. It's a disaster for the underlying LSM DB, endless table compaction and huge write amplification.

How to understand the endless table compaction?

**Comment by jongrun** [comment]
> The purpose of partition (and the suffix `commitNum%t.back.HistPtnFactor`) is to make the nodes better compressed.

In my understanding, it is to make the key of the nodes better compressed, instead of the node itself. Right?

**Comment by jongrun** [comment]
> > Why it is more LSM DB friendly with smaller HistPtnFactor?
> 
> Less table compaction, leads to higher DB write throughput. It'll be perfect if set HistPtnFactor to 1, but would lose the benefit of compression.

Why does smaller HistPtnFactor lead to less table compaction? Is it about overlaps between ssTables?

**Comment by qianbin** [comment]
> How to understand the endless table compaction?
You can do a stress test which keeps inserting large amount of data, then you'll see the insert process paused at some time, and slower and slower.

> In my understanding, it is to make the key of the nodes better compressed, instead of the node itself. Right?

The node itself. The code snippet shows that.

**Comment by qianbin** [comment]
> Why does smaller HistPtnFactor lead to less table compaction? Is it about overlaps between ssTables?

No. Smaller HistPtnFactor increases the probability that a node and its modified versions stored in the same block(the base unit of LSM DB, not blockchain's block), which is default compressed with snappy.

**Comment by jongrun** [comment]
> The node itself. The code snippet shows that.

How can the partition ID in key (which is not included in node) influence the node compressing?

**Comment by jongrun** [comment]
> Sorry, I misunderstood the last question.
> With larger HistPtnFactor, more nodes share one same partition ID, which means a particular node and its modified versions will more likely be stored in one block(the base unit of LSM DB, not blockchain's block), and will be well compressed just like the code snippet showing.

Got it. My understanding:
1. Hash-based keys is totally random, which makes ssTables almost overlap with all next-level tables. That reduces performance of compaction.
2. BlockNum+Name+Path makes the keys in order and ssTables rarely overlap with next-level tables, which is nice for compaction.
3. Larger HistPtnFactor make more nodes (even with different block number) share one same partition ID. A particular node and its modified versions usually have large intersection, so if they stored in one block (the base unit of LSM DB), they will be better compressed. Larger HistPtnFactor makes it.
4. Larger HistPtnFactor makes ssTables overlap with more next-level tables and so influences the compaction. So a proper HistPtnFactor should be selected to balance the compaction and compression.

If there is any mistake, please point it out, thank you.

![image](https://leveldb-handbook.readthedocs.io/zh/latest/_images/major_compaction.jpeg)

**Comment by qianbin** [comment]
> Got it. My understanding:
> 
> 1. Hash-based keys is totally random, which makes ssTables almost overlap with all next-level tables. That reduces performance of compaction.
> 2. BlockNum+Name+Path makes the keys in order and ssTables rarely overlap with next-level tables, which is nice for compaction.
> 3. Larger HistPtnFactor make more nodes (even with different block number) share one same partition ID. A particular node and its modified versions usually have large intersection, so if they stored in one block (the base unit of LSM DB), they will be better compressed. Larger HistPtnFactor makes it.
> 4. Larger HistPtnFactor makes ssTables overlap with more next-level tables and so influences the compaction. So a proper HistPtnFactor should be selected to balance the compaction and compression.
> 
> If there is any mistake, please point it out, thank you.

Totally right.

**Comment by jongrun** [comment]
> Got it. My understanding:
> 
> 1. Hash-based keys is totally random, which makes ssTables almost overlap with all next-level tables. That reduces performance of compaction.
> 2. BlockNum+Name+Path makes the keys in order and ssTables rarely overlap with next-level tables, which is nice for compaction.
> 3. Larger HistPtnFactor make more nodes (even with different block number) share one same partition ID. A particular node and its modified versions usually have large intersection, so if they stored in one block (the base unit of LSM DB), they will be better compressed. Larger HistPtnFactor makes it.
> 4. Larger HistPtnFactor makes ssTables overlap with more next-level tables and so influences the compaction. So a proper HistPtnFactor should be selected to balance the compaction and compression.

Additional, name + path make keys share common prefix, and so can take advantage of leveldb key compression.
![](https://leveldb-handbook.readthedocs.io/zh/latest/_images/entry_format.jpeg)

**Comment by darrenvechain** [comment]
Closing as it's marked as stale and without activity
