### ISSUE TITLE
Why not use the account address as the trie name?

### ISSUE THREAD

**Issue by jongrun** [vechain/thor#583]
https://github.com/vechain/thor/blob/6aa5f94a1e379662931dd153e577fcc17239c56b/state/state.go#L463-L471

Why use BlockNum+BlockConflicts+storageTrieCreationCount (which results in extra storage space for storageID) as the trie name? For which of the reasons following or any other ones? 
- To distinguish new and old accounts which are created by CREATE2 with the same args (the old one is selfdestruct and the new one reuses the same address) ?
- LSM DB friendly?
- To accelerate node iteration?
- To reduce the key length?

**Comment by jongrun** [comment]
> > * To distinguish new and old accounts which are created by CREATE2 with the same args (the old one is selfdestruct and the new one reuses the same address) ?
> 
> It's the reason.

What‘s the problem if we use the account address as the trie name? Though there are accounts with the same address, they are in different state tries and we can distinguish them by block height.

**Comment by jongrun** [comment]
> Why use BlockNum+BlockConflicts+storageTrieCreationCount (which results in extra storage space for storageID) as the trie name? For which of the reasons following or any other ones?
> 
> * To distinguish new and old accounts which are created by CREATE2 with the same args (the old one is selfdestruct and the new one reuses the same address) ?
> * LSM DB friendly?
> * To accelerate node iteration?
> * To reduce the key length?

Or isn't it just for LSM DB friendly?

**Comment by jongrun** [comment]
> Fork, blocks have same height.

Can Add blockConflict. But that's not my key point. My point is that why not use address(+BlockConflict) but BlockNum+BlockConflicts+storageTrieCreationCount. What's the primary reason?

**Comment by qianbin** [comment]
> Can Add blockConflict. But that's not my key point. My point is that why not use address(+BlockConflict) but BlockNum+BlockConflicts+storageTrieCreationCount. What's the primary reason?

address(+BlockConflict) is obviously unacceptable, due to the self-destruct op.
The primary reason is to give each storage trie a unique id, in consideration of safety.

**Comment by jongrun** [comment]
> address(+BlockConflict) is obviously unacceptable, due to the self-destruct op.
> The primary reason is to give each storage trie a unique id, in consideration of safety.

But the nodes is located by key blockNumber+trieName+path+conflicts. In a blockNumber+conflicts context, any account address is unique.

**Comment by qianbin** [comment]
> But the nodes is located by key blockNumber+trieName+path+conflicts. In a blockNumber+conflicts context, any account address is unique.

That's ok to construct storageID by address + blockNumber + conflicts. While use creationCount instead of address gets shorter storage trie name.

**Comment by jongrun** [comment]
> That's ok to construct storageID by address + blockNumber + conflicts. While use creationCount instead of address gets shorter storage trie name.

No, I mean that trieName = storageID = address. There are blockNumber+conflicts in the key of trie nodes.

**Comment by jongrun** [comment]
> Seems it's OK to use address.

If it's ok, what's the advantage of BlockNum+BlockConflicts+storageTrieCreationCount, which brings extra storage space and complexity.

**Comment by jongrun** [comment]
> Seems it's OK to use address.

If it's ok, what's the advantage of BlockNum+BlockConflicts+storageTrieCreationCount, which brings extra storage space and complexity.

**Comment by qianbin** [comment]
> If it's ok, what's the advantage of BlockNum+BlockConflicts+storageTrieCreationCount, which brings extra storage space and complexity.

If you want to prune storage tries, you have to maintain the link from account object to its storage trie, like https://github.com/vechain/thor/blob/ed4f1765a213d68298059672d6a58f060d65a3f8/state/account.go#L18 . You can replace StorageID with address if address is preferred.

**Comment by jongrun** [comment]
> If you want to prune storage tries, you have to maintain the link from account object to its storage trie

If address is used as trie name, there is no need to maintain storageID, because address is in account object. StorageCommitNum and StorageDistinctNum are needed and they can be stored as seqNum just as hash nodes do.

**Comment by jongrun** [comment]
> You can replace StorageID with address if address is preferred.

My original intention is just to understand the necessity or advantage of storageID.

**Comment by qianbin** [comment]
> > If you want to prune storage tries, you have to maintain the link from account object to its storage trie
> 
> If address is used as trie name, there is no need to maintain storageID, because address is in account object. StorageCommitNum and StorageDistinctNum are needed and they can be stored as seqNum just as hash nodes do.

There's no address in account object actually. The account trie is a secure trie which means addresses can't be retrieved when iterating accounts.

**Comment by qianbin** [comment]
> > You can replace StorageID with address if address is preferred.
> 
> My original intention is just to understand the necessity or advantage of storageID.

Address or storageID is necessary if you want tries prunable. And the advantage of storageID is its compact format.

**Comment by jongrun** [comment]
> There's no address in account object actually. The account trie is a secure trie which means addresses can't be retrieved when iterating accounts.

Oh, yes. Sorry. The address has to been got from a preimage db or stored in AccountMetaData.

**Comment by jongrun** [comment]
> Address or storageID is necessary if you want tries prunable. And the advantage of storageID is its compact format.

Another question. For storageID, the BlockConflicts is unecessary, that is, BlockNum+storageTrieCreationCount is ok. Isn't it?

**Comment by qianbin** [comment]
> > Address or storageID is necessary if you want tries prunable. And the advantage of storageID is its compact format.
> 
> Another question. For storageID, the BlockConflicts is unecessary, that is, BlockNum+storageTrieCreationCount is ok. Isn't it?

Yes for a blockchain with finality.

**Comment by jongrun** [comment]
> Yes for a blockchain with finality.

I mean that the BlockConflicts (in storageID) is unecessary even for a blockchain with fork, because the Conficts in nodes (leaf nodes of state trie or hash nodes) is enough.
Or can you take a example for a safety problem caused by using storageID=BlockNum+storageTrieCreationCount (without BlockConflicts) as trie name.

**Comment by qianbin** [comment]
> I mean that the BlockConflicts (in storageID) is unecessary even for a blockchain with fork, because the Conficts in nodes (leaf nodes of state trie or hash nodes) is enough.
> Or can you take a example for a safety problem caused by using storageID=BlockNum+storageTrieCreationCount (without BlockConflicts) as trie name.

For leafbank, omit BlockConflicts may get wrong state in critical case.

**Comment by jongrun** [comment]
> For leafbank, omit BlockConflicts may get wrong state in critical case.

The leaves in leafbank is always before steady number, so the absence of BlockConflicts in storageID doesn't matter.
Or do you mean that the steady number may not be steady in fact?

**Comment by qianbin** [comment]
> The leaves in leafbank is always before steady number, so the absence of BlockConflicts in storageID doesn't matter.
> Or do you mean that the steady number may not be steady in fact?

Steady is not finalized.
