### ISSUE TITLE
Transactions of VET

### ISSUE THREAD

**Issue by Swornatoya** [vechain/thor#599]
For a transaction in VET there are clauses and also token transferred, in token transferred there are multiple transfers. How is the amount calculated here.
For example if I consider the transaction hash 0x401f40721b640b78b8690742157a8bf3b6c3916756ac9aaf3cf2ee2f10d73580
Total transfer is 1,000.00 VET

the Token transferred has the below details as shown in the attached screenshot. Does the total transfer amount is same as in the clause1 in the image

![image](https://github.com/vechain/thor/assets/101313232/d9697968-9b78-49ab-ae31-99c92af61bfc)

Is this clause only for VTO and if so then I could see there are two transfers then how does the VET values is 1000.00 VET
![image](https://github.com/vechain/thor/assets/101313232/4a3cd025-88c0-4f07-a99d-8c0a84a1cd17)

**Comment by libotony** [comment]
The token transfer is detected by the event log, there is an event called `Transfer` for tokens(ERC20/VIP180). And the transfer page is dedicated to VET transfer.

**Comment by libotony** [comment]
Total transfer calculates the value defined in the clauses. If I am understanding correctly(since I am not the contract dev), the transfer events were triggered inside the contract call.

**Comment by Swornatoya** [comment]
But if we see the below image the the value defined in the clauses and the total transfer does not match.
![image](https://github.com/vechain/thor/assets/101313232/166ee5c8-264a-44b1-b44c-e6e8a2b3a172)

**Comment by libotony** [comment]
The VET value just means the value set to the clause. In the meantime, the transfer log is the output(or we can say outcome) of the transaction. It means how many VET transfers happened in one transaction/clause.

**Comment by Swornatoya** [comment]
Then how about the fees being deducted it is in VTHO so does this mean that a particular address has balance in VTO and VTHO. Is it different from the VTHO tokens transferred

**Comment by libotony** [comment]
Transaction fee will be reflected in `gasPayer` and `paid` field of the transaction receipt, and it's deducted in in `VTHO`

> Then how about the fees being deducted it is in VTHO so does this mean that a particular address has balance in VTO and VTHO. Is it different from the VTHO tokens transferred

**Comment by Swornatoya** [comment]
@libotony , When I tried calculating the value of VET and VTHO for one particular address 0xdA035cC0c5A64cDAadc2f921270c14C764448C95. The VET amount matches but somehow the VTHO does not. I tried calculating by downloading all the transactions in an excel format from the transfers tab : https://explore.vechain.org/accounts/0xda035cc0c5a64cdaadc2f921270c14c764448c95/transfer

VET value from excel : 2634.5
VTHO value from excel: 1472.55
	
Fee in VTHO : -11.97
Total Fee: -720.58
	
VTHO after deducting only VTHO fee: 1460.58
VTHO after deducting Total Fee: 751.97
	
VET amount in explorer: 2634.5
VTHO amount in explorer: 396.62

Am I missing anything here.

**Comment by libotony** [comment]
F

> @libotony , When I tried calculating the value of VET and VTHO for one particular address 0xdA035cC0c5A64cDAadc2f921270c14C764448C95. The VET amount matches but somehow the VTHO does not. I tried calculating by downloading all the transactions in an excel format from the transfers tab : https://explore.vechain.org/accounts/0xda035cc0c5a64cdaadc2f921270c14c764448c95/transfer
> 
> VET value from excel : 2634.5 VTHO value from excel: 1472.55
> 
> Fee in VTHO : -11.97 Total Fee: -720.58
> 
> VTHO after deducting only VTHO fee: 1460.58 VTHO after deducting Total Fee: 751.97
> 
> VET amount in explorer: 2634.5 VTHO amount in explorer: 396.62
> 
> Am I missing anything here.

You need to include the VTHO transfer amount and the generation of VTHO https://docs.vechain.org/thor/learn/two-token-design

**Comment by darrenvechain** [comment]
Closing as it's marked as stale and without activity
