### ISSUE TITLE
VTHO Tokens Data. (Generated value & paid value)

### ISSUE THREAD

**Issue by shassal** [vechain/thor#616]
Hi All,

Can anyone help me with the difference between **generated** value of VTHO Token data and Paid **VTHO** Token data?
I am searching for the address https://explore.vechain.org/accounts/0xb3ae0d357102f8a01e95519fab30b45a5ab84f61/

Getting VTHO Token data AS **31.89** **vtho** but I can't see any transfers.

Any help would be appreciated,
Thanks.

**Comment by libotony** [comment]
Hi @shassal VTHO is the utility token for tx fee-paying, holding VET you will get VTHO, which you can learn more from doc https://docs.vechain.org/introduction-to-vechain/dual-token-economic-model/vethor-vtho#do-i-earn-vtho. So you have `31.89 VTHO` without anyone transferring to you, generating VTHO does not show any transfer event.

**Comment by libotony** [comment]
Usually, we recommend using the data returned by the node API

**Comment by shassal** [comment]
Okay, thanks
