### ISSUE TITLE
solo --on-demand flag - not producing blocks on txns added to txpool

### ISSUE THREAD

**Issue by decent-dev** [vechain/thor#80]
## OS Version: 
OSX 

## Commit hash : (if develop)
a9b9ea581bfa656bfd9a9a89fa7d8440ad7cf12c

## Expected behavior
While running bin/thor solo --on-demand, while sending a simple web3.eth.sendTransaction (or any other transaction) the transaction should ideally be added to a block that would be packed and added to the running chain instantly.

## Actual behavior
Thor doesn't seem to do anything with the --on-demand flag on. With --verbosity 9, we can see that it's being added to the txpool - however, a block isn't produced at the time.

`DBUG[07-23] tx added                                 pkg=txpool id=0x1b14bc0ed79c41d6881036bb6dcf698a6248fbeda12337392f254ef977e4b0e4`

## Steps to reproduce the behavior

1. Run bin/thor solo --on-demand --verbosity 9
2. Send any transaction

**Comment by libotony** [comment]
@decent-dev can you show me the detail of the tx?

**Comment by decent-dev** [comment]
```
web3.eth.accounts.wallet.add(PRIVATE_KEY)
let tx = await web3.eth.sendTransaction({
  from: '0x7567d83b7b8d80addcb281a71d54fc7b3364ffed',
  to: '0xF2D6fF4adf714d994E1bFBA2568432c1C8b6F257',
  value: 100,
})
```

And the logs in thor

```
INFO[07-23] prepared to pack block 
DBUG[07-23] tx added pkg=txpool id=0xb5bdfceaf328623879f062686c437572390b000bd4d30b123e324dbf2edeeb4b
```

This is just an example transaction- our contract deployment scripts also don't work right now with --on-demand. 

However, everything works fine with --network test or in solo without the --on-demand flag.

**Comment by libotony** [comment]
can you run `thor --version` and comment with the output?

**Comment by decent-dev** [comment]
`Thor version 1.0.1-a9b9ea5-dev`

**Comment by libotony** [comment]
@decent-dev  Are you sure in this version `Thor version 1.0.1-a9b9ea5-dev` on demand mode not working? I just  tried and seems it's working, can you check again?

**Comment by decent-dev** [comment]
Yes, it's the same version. To make sure everything was setup right I did a clean install right now and I still face the same issue. 

solo without on-demand works, however on-demand seems to not do anything.

**Comment by libotony** [comment]
The action you describe is really the old code's action: 
```
INFO[07-23] prepared to pack block 
DBUG[07-23] tx added pkg=txpool id=0xb5bdfceaf328623879f062686c437572390b000bd4d30b123e324dbf2edeeb4b
```
New code's action is:
```
INFO[07-23|23:42:16] prepared to pack block
DBUG[07-23|23:42:20] tx added                                 pkg=txpool id=0xd121c0fffdf25c28ae88d3839bc7100170a0b02c4eff1fef5e3af01914033c22
INFO[07-23|23:42:20] new Tx                                   id=0xd121c0fffdf25c28ae88d3839bc7100170a0b02c4eff1fef5e3af01914033c22 signer=0x7567d83b7b8d80addcb281a71d54fc7b3364ffed
```
please try
```
make clean
make thor
```

**Comment by decent-dev** [comment]
I ran make again as instructed above however It's pretty much the same output minus the "new Tx" output. It does show up on testnet or on solo without --on-demand though.

I've attached a couple of screenshots for your reference.

<img width="571" alt="screen shot 2018-07-24 at 4 28 10 pm" src="https://user-images.githubusercontent.com/30058929/43134406-9dbb51ae-8f5f-11e8-978b-2f299a9012e0.png">

<img width="570" alt="screen shot 2018-07-24 at 4 28 07 pm" src="https://user-images.githubusercontent.com/30058929/43134456-bf59ea64-8f5f-11e8-9329-cf0bb49c6f5f.png">

**Comment by libotony** [comment]
@decent-dev  hmmm that's really wired, which directory are your thor source code located? can you verify that on another computer?

**Comment by libotony** [comment]
@molekilla please update the source code to the latest version, it's a fixed issue and it's wired that @decent-dev still get old code running

**Comment by libotony** [comment]
@decent-dev @molekilla any update ?

**Comment by molekilla** [comment]
is working for me. thanks.
