### ISSUE TITLE
🐛 [BUG] - <title>编译时候报错

### ISSUE THREAD

**Issue by godlovericea** [vechain/thor#849]
### Description

我的需求是：链接VeChain 主网，向指定的 地址 发送 VET 币，构建链上交易。
目前已知参数，发送方私钥，接收方地址，需要通过代码实现（go语言）

Build Error: go test -c -o d:\cvs_git\kerying_learn\address\__debug_bin90001488.exe -gcflags all=-N -l .
# github.com/vechain/thor/v2/muxdb
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\muxdb\muxdb.go:86:11: ldbOpts.OverflowPrefix undefined (type opt.Options has no field or method OverflowPrefix)
# github.com/vechain/thor/v2/abi
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\abi.go:60:5: unknown field Const in struct literal of type "github.com/ethereum/go-ethereum/accounts/abi".Method
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\abi.go:65:26: ethMethod.Id undefined (type "github.com/ethereum/go-ethereum/accounts/abi".Method has no field or method Id)
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\event.go:28:22: event.Id undefined (type *"github.com/ethereum/go-ethereum/accounts/abi".Event has no field or method Id)
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\event.go:51:9: too many return values
	have ([]interface{}, error)
	want (error)
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\event.go:51:40: too many arguments in call to e.argsWithoutIndexed.Unpack
	have (interface{}, []byte)
	want ([]byte)
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\method.go:33:18: m.method.Const undefined (type *"github.com/ethereum/go-ethereum/accounts/abi".Method has no field or method Const)
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\method.go:50:9: too many return values
	have ([]interface{}, error)
	want (error)
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\method.go:50:40: too many arguments in call to m.method.Inputs.Unpack
	have (interface{}, []byte)
	want ([]byte)
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\method.go:63:9: too many return values
	have ([]interface{}, error)
	want (error)

C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\method.go:63:36: too many arguments in call to m.method.Outputs.Unpack
	have (interface{}, []byte)
	want ([]byte)
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\abi\method.go:63:9: too many errors
# github.com/vechain/thor/v2/vm
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\jump_table.go:27:34: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\interpreter.go:49:18: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\gas.go:41:30: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\gas_table.go:65:32: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\gas_table.go:91:34: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\gas_table.go:117:26: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\gas_table.go:169:24: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\gas_table.go:193:28: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\gas_table.go:217:31: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\gas_table.go:243:31: undefined: params.GasTable
C:\Users\Administrator\go\pkg\mod\github.com\vechain\thor\v2@v2.1.3\vm\gas_table.go:243:31: too many errors (exit status 1)

### Reproduction URL

https://github.com/godlovericea

### Reproduction steps

```bash
package address

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"testing"

	"github.com/ethereum/go-ethereum/common/hexutil"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/ethereum/go-ethereum/rlp"
	"github.com/stretchr/testify/assert"
	"github.com/vechain/thor/v2/api/transactions"
	"github.com/vechain/thor/v2/genesis"
	"github.com/vechain/thor/v2/tx"
)

var ts *http.Server

func Test_SendTx(t *testing.T) {
	var blockRef = tx.NewBlockRef(0)
	var expiration = uint32(10)
	var gas = uint64(21000)

	tx := new(tx.Builder).
		BlockRef(blockRef).
		ChainTag(74).
		Expiration(expiration).
		Gas(gas).
		Build()
	sig, err := crypto.Sign(tx.SigningHash().Bytes(), genesis.DevAccounts()[0].PrivateKey)
	if err != nil {
		t.Fatal(err)
	}
	tx = tx.WithSignature(sig)
	rlpTx, err := rlp.EncodeToBytes(tx)
	if err != nil {
		t.Fatal(err)
	}

	res := HttpPostAndCheckResponseStatus(t, ts.URL+"/transactions", transactions.RawTx{Raw: hexutil.Encode(rlpTx)}, 200)
	var txObj map[string]string
	if err = json.Unmarshal(res, &txObj); err != nil {
		t.Fatal(err)
	}
	assert.Equal(t, tx.ID().String(), txObj["id"], "should be the same transaction id")
}

func HttpPostAndCheckResponseStatus(t *testing.T, url string, obj interface{}, responseStatusCode int) []byte {
	data, err := json.Marshal(obj)
	if err != nil {
		t.Fatal(err)
	}
	res, err := http.Post(url, "application/x-www-form-urlencoded", bytes.NewReader(data)) // nolint: gosec
	if err != nil {
		t.Fatal(err)
	}
	assert.Equal(t, responseStatusCode, res.StatusCode, fmt.Sprintf("status code should be %d", responseStatusCode))
	r := ParseBytesBody(t, res.Body)
	res.Body.Close()
	return r
}

func ParseBytesBody(t *testing.T, body io.ReadCloser) []byte {
	r, err := io.ReadAll(body)
	if err != nil {
		t.Fatal(err)
	}
	return r
}
编译过不去。
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Windows

**Comment by libotony** [comment]
Looks like you are adding our project and the latest go-ethereum as dependencies, we are currently using a self-maintained go-ethereum fork and go-leveldb fork as our dependencies. This may cause issues with compilation in your scenario.  If feasible, please refrain from importing the latest version of go-ethereum to ensure compatibility with our project as a dependency.

**Comment by otherview** [comment]
Hey @godlovericea if you're still having trouble with your setup, please reach out over [Discord](https://discord.com/invite/vechain).
