### ISSUE TITLE
Keys Creation, Management and Storage with Hardware Security Modules (HSM)

### ISSUE THREAD

**Issue by nathanawmk** [vechain/thor#93]
Hi there,

Please notice that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel.

## OS Version: 
Windows/Linux/OSX 

## Expected behavior
Tell us what should happen.

## Actual behavior
Tell us what happens instead. Provide a log message if relevant.

**Comment by libotony** [comment]
Regarding the account creation, thor is using the same mechanism as ethereum

**Comment by nathanawmk** [comment]
how can we secure the private keys that sit on Geth?

**Comment by libotony** [comment]
Go-ethereum stores the private key in KeyStoreV3 format
