### ISSUE TITLE
No paste password for withdrawals on OSX mobile APP

### ISSUE THREAD

**Issue by horsecoin** [vechain/thor#95]
I tried to withdraw my VTHO from my VeChainThor Wallet OSX mobile app on my iPhone X and at the end it asks for my password, but the input text field does not have the paste feature working. 

My password is very long so this is very inconvenient.  Please Fix VeChain!

**Comment by andyden9** [comment]
I think disabling paste function to password field is essential for safety, since the pasteboard is shared between apps.

**Comment by horsecoin** [comment]
Thanks that is is correct. I guess VeChain needs to make a secure pastebin system for us then.  The app is sick, it uses my face to open the app, I don't see why it can't use my face to access my private paste bin with password and paste it in for me.
